src/functionalTest/kotlin/com/autonomousapps/utils/AndroidProject.kt

My goal was to make it easier to have actual files in the tests themselves, so that it would be easier to define more diverse tests.
I introduced base project classes, without breaking the existing hierarchy of modules.
I searched in the gradle code if there were a few classes that we could use to have a real DSL to create projects. I didn't find one but a few things are pretty close, we should ask Luke when we meet him.
I am looking for something like : 
```kotlin
whithBuildFile {
plugins {
id('java-library')
id('org.jetbrains.kotlin.jvm')
}
dependencies {
implementation platform('org.jetbrains.kotlin:kotlin-bom')
implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
api 'org.apache.commons:commons-math3:3.6.1'
implementation 'com.google.guava:guava:28.0-jre'
}  
}
```
It would be …

Add a small test DSL.

---

README.md

It might conflict with the other PR changing the README, just keep both versions.

Add badge for version

---

.travis.yml
README.md

Still trying it. 
To setup travis : 
* go to https://travis-ci.com/getting_started
* click on the button Activate all repositories using github apps
* select your project (dependency-analysis-android-gradle-plugin)
* merge my PR
* from now on you should be able to see all PRs being built
I also add a build badge to the README in a seperate commit. It should work when travis is setup for your repo.

setup travis CI

---

src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/ArtifactToComponentTransformer.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyReportTask.kt

No more project usages in task, which is very positive.

Further improved configuration of DependencyReportTask.

---

.travis.yml

Also, Travis randomly decided to deactivate the repo. Hopefully I've solved that?

Updated .travis.yml to run more tests.

---

src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsAnalysisTask.kt

This is a prerequisite for making more concrete recommendations in the terminal reports (such as the ABI report).

Added configuration names to Dependency model.

---

src/functionalTest/kotlin/com/autonomousapps/AbstractFunctionalTests.kt
src/functionalTest/kotlin/com/autonomousapps/AndroidFunctionalTests.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/AndroidProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/adviceTestProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/dependencies.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/sources.kt
src/main/kotlin/com/autonomousapps/internal/Advisor.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
src/main/kotlin/com/autonomousapps/tasks/InlineMemberExtractionTask.kt
src/test/kotlin/com/autonomousapps/internal/AdvisorTest.kt

Still need to sanity check against a real project.

Add tests for new formal "advice"

---

CHANGELOG.md
README.md
gradle/wrapper/gradle-wrapper.properties
src/functionalTest/kotlin/com/autonomousapps/utils/TestMatrix.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/moshi.kt
src/main/kotlin/com/autonomousapps/tasks/FailOrWarnTask.kt

Need to update changelog and readme still.

Added configurable error states

---

CHANGELOG.md
README.md
src/functionalTest/kotlin/com/autonomousapps/AndroidFunctionalTests.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/AndroidProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/RootProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/adviceTestProject.kt
src/functionalTest/kotlin/com/autonomousapps/utils/runner.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/Advisor.kt
src/main/kotlin/com/autonomousapps/internal/outputDirectories.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceAggregateReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/FailOrWarnTask.kt
src/test/kotlin/com/autonomousapps/internal/AdvisorTest.kt

Not quite ready for release, but let's see if what's here builds.

Adding error-handling DSL.

---

build.gradle.kts
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/ConstantPoolParser.kt
src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
src/main/kotlin/com/autonomousapps/internal/dependencyAnalysis.kt
src/main/kotlin/com/autonomousapps/internal/utils.kt
src/test/kotlin/com/autonomousapps/internal/JarReaderTest.kt
src/test/resources/shelter/core/classes-jar-expected.txt
src/test/resources/shelter/db/classes-jar-expected.txt

Fixes https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/57

Support detection of constants

---

src/functionalTest/groovy/com/autonomousapps/AbsractFunctionalTest.groovy
src/functionalTest/groovy/com/autonomousapps/AndroidTests.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/KtxProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/ViewBindingProject.kt
src/functionalTest/kotlin/com/autonomousapps/utils/runner.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/advice/AdvicePrinter.kt
src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt
src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt
src/main/kotlin/com/autonomousapps/internal/advice/FilterSpec.kt
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseAggregateReportTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/87.

ISS-87. Provided support for optionally ignoring -ktx dependencies.

---

CHANGELOG.md
build.gradle.kts
src/functionalTest/groovy/com/autonomousapps/AbsractFunctionalTest.groovy
src/functionalTest/groovy/com/autonomousapps/JvmTests.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/ProjectDirProvider.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/RootProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/SingleProject.kt
src/functionalTest/kotlin/com/autonomousapps/utils/runner.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt

Fixes https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/92.

ISS-92. Fixed. Plugin provides advice from root project's source.

---

CHANGELOG.md
build.gradle.kts
src/functionalTest/groovy/com/autonomousapps/AndroidTests.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/AppCompatProject.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
src/main/kotlin/com/autonomousapps/internal/dependencyAnalysis.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/outputDirectories.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/internal/utils/xml.kt
src/main/kotlin/com/autonomousapps/tasks/AndroidResToResAnalysisTask.kt
src/main/kotlin/com/autonomousapps/tasks/AndroidResToSourceAnalysisTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
src/main/kotlin/com/autonomousapps/tasks/ManifestPackageExtractionTask.kt
src/test/kotlin/com/autonomousapps/tasks/MisusedDependencyDetectorTest.kt

Fixes https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/97

Read public.txt to find res usage by res files.

---

src/functionalTest/kotlin/com/autonomousapps/fixtures/CompileOnlyTestProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/DataBindingProject.kt
src/main/kotlin/com/autonomousapps/internal/AnalyzedJar.kt
src/main/kotlin/com/autonomousapps/internal/ArtifactToComponentTransformer.kt
src/main/kotlin/com/autonomousapps/internal/ConstantPoolParser.kt
src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
src/main/kotlin/com/autonomousapps/tasks/AndroidResToResAnalysisTask.kt
src/main/kotlin/com/autonomousapps/tasks/AndroidResToSourceAnalysisTask.kt
src/main/kotlin/com/autonomousapps/tasks/ConstantUsageDetectionTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
src/main/kotlin/com/autonomousapps/tasks/ImportFinderTask.kt
src/main/kotlin/com/autonomousapps/tasks/InlineMemberExtractionTask.kt
src/main/kotlin/com/autonomousapps/tasks/ManifestPackageExtractionTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/106

Interning Utils.kt#asString and using specialized *toSet functions more.

---

src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/outputDirectories.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt

Adds a pretty report for each project. 
I want to do the same for the aggregate report task in the root project in a follow up PR.

Use a pretty report file for advices

---

src/functionalTest/groovy/com/autonomousapps/android/CoreKtxSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/ServiceLoaderSpec.groovy
src/functionalTest/groovy/com/autonomousapps/fixtures/AndroidResourceProject.groovy
src/functionalTest/groovy/com/autonomousapps/fixtures/DefaultAndroidProject.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/AndroidLayout.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/AndroidProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/ServiceLoaderProject.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt
src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt

Not finished, but I want to merge it. Let's see if I broke anything!

Serviceloader

---

src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/AnalyzedJar.kt
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/internal/advice/AdvicePrinter.kt
src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
src/main/kotlin/com/autonomousapps/tasks/AdvicePrinterTask.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
src/test/kotlin/com/autonomousapps/internal/ConsoleReportTest.kt
src/test/kotlin/com/autonomousapps/internal/advice/AdvisorTest.kt

Model console report and dissociate display task for humans

---

.github/workflows/pr.yml
settings.gradle.kts

Add GithubAction run link in BuildScan

---

src/functionalTest/groovy/com/autonomousapps/fixtures/jvm/Dependency.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/GenericsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GenericsProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/GenericsUsageDetectionTask.kt
src/test/kotlin/com/autonomousapps/tasks/MisusedDependencyDetectorTest.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/148

Detect types used in a generics context.

---

src/main/kotlin/com/autonomousapps/AbstractExtension.kt

This is nicer to handle than having to try/catch

Make adviceOutputFor return nullable

---

src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/functionalTest/groovy/com/autonomousapps/fixtures/jvm/Dependency.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/CompileSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/CompileProject.groovy
src/functionalTest/kotlin/com/autonomousapps/jvm/projects/CompileAdvice.kt
src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/159

Add tests verifying awareness of compile configuration.

---

src/functionalTest/groovy/com/autonomousapps/fixtures/jvm/Plugin.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/ApplicationSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/ApplicationProject.groovy
src/functionalTest/kotlin/com/autonomousapps/jvm/projects/ApplicationAdvice.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt

Resolve https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/160

Added support for the application plugin.

---

CHANGELOG.md
src/main/kotlin/com/autonomousapps/tasks/ArtifactsAnalysisTask.kt

Fixes https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/164

Fixed build cache issue with ArtifactsAnalysisTask.

---

src/functionalTest/groovy/com/autonomousapps/android/AdviceSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/CoreKtxSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidResourceProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DefaultAndroidProject.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/AndroidProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/adviceTestProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/dependencies.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/jvmModules.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/advice/Advice.kt
src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt
src/main/kotlin/com/autonomousapps/internal/advice/filter/FilterSpec.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/FailOrWarnTask.kt
src/test/kotlin/com/autonomousapps/internal/ConsoleReportTest.kt

Solves #126 . 
There was also a little issue in a different test, I hope you're ok that I fix it here.

Add a filter for unused annotation processors.

---

src/functionalTest/groovy/com/autonomousapps/android/AdviceSpec.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt

Must update wiki after this is merged.

Incrementally improved the DSL.

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
scripts/functionalTests.sh
src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/TestSourceSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidThreeTenProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/TestSourceProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/PostProcessingSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/PostProcessingProject2.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePlugin3_5.kt
src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePlugin4_0.kt
src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePlugin4_1.kt
src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePlugin4_2.kt
src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePluginFactory.kt
src/main/kotlin/com/autonomousapps/internal/android/BaseAndroidGradlePlugin.kt
src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/tasks/classAnalysisTasks.kt
src/test/groovy/com/autonomousapps/internal/android/AndroidGradlePluginFactorySpec.groovy
src/test/kotlin/com/autonomousapps/internal/ClassSetReaderTest.kt
src/test/kotlin/com/autonomousapps/internal/JarReaderTest.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/47.
Not quite ready yet.

Test support

---

src/functionalTest/groovy/com/autonomousapps/jvm/GradleApiSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GradleApiProject.groovy
src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
src/main/kotlin/com/autonomousapps/tasks/FindUnusedProcsTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/199

Reproduced and resolved issue 199, gradleApi() is an OpaqueComponentIdentifier

---

src/functionalTest/groovy/com/autonomousapps/jvm/ConstantsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/RedundantPluginsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/RedundantPluginsProject.groovy
src/main/kotlin/com/autonomousapps/advice/PluginAdvice.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/209.

Added a functional test for onRedundantPlugins.

---

src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/210

Fix redundant advice in transitive dependencies report.

---

src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmSourceSet.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/211.
Basically was relying on set logic when I needed a merged map.

Fixed issue with incorrectly assigning the test variant to a dependency.

---

CHANGELOG.md
src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/SpringBootSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/SpringBootProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/222.

For Spring Boot projects, do not recommend api dependencies.

---

build.gradle.kts

Would also like to use Groovy 3, but that seems to run afoul of Gradle.

Use Spock 2.0-M3 for unit and functional tests.

---

src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/tasks/FindUnusedProcsTask.kt
src/main/kotlin/com/autonomousapps/tasks/InlineMemberExtractionTask.kt
src/main/kotlin/com/autonomousapps/tasks/classAnalysisTasks.kt

Maybe resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/239.

Don't analyze module-info.class files.

---

CHANGELOG.md
src/functionalTest/groovy/com/autonomousapps/android/NativeLibSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/NativeLibProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsAnalysisTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindNativeLibsTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Repository.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/252.
This is not quite done yet (I'd like to add a test).

Detect AARs with bundled native libs.

---

CHANGELOG.md
README.asciidoc
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/graph/Node.kt
src/main/kotlin/com/autonomousapps/graph/Reason.kt
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyGraphAggregationTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyGraphTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonAggregationTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonableDependencyTask.kt

Sample usage:
```
$ ./gradlew app:reason --id com.github.ChuckerTeam.Chucker:library-no-op
```

Improve graph/reason UX

---

CHANGELOG.md
src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
src/test/kotlin/com/autonomousapps/extension/BehaviorTest.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/273.

Resolves Issue 273: failure to combine global and project-specific behavior.

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/com/autonomousapps/internal/AnalyzedJar.kt
src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/JvmConstantDetector.kt
src/main/kotlin/com/autonomousapps/services/InMemoryCache.kt
src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
src/main/kotlin/com/autonomousapps/tasks/InlineMemberExtractionTask.kt

Attempt to resolve https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/274.
To test it out, run
```
./gradlew buildHealth -Ddependency.analysis.cache.max=1000
```
where `1000` can be any valid `long` value. If this resolves the problem, I will consider providing a DSL for this.

WIP. Resolve Issue 274 by providing configurable cache size.

---

src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisSubExtension.kt

Resolves (?) https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/241
Need to ensure I have a test that actually uses the subextension.

Trying to resolve issue 241.

---

src/main/kotlin/com/autonomousapps/advice/ReasonableDependency.kt
src/main/kotlin/com/autonomousapps/graph/Node.kt
src/main/kotlin/com/autonomousapps/graph/Reason.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
src/main/kotlin/com/autonomousapps/tasks/ManifestPackageExtractionTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonableDependencyTask.kt

Incrementally hydrating the ReasonableDependency output to include more information.

Added actual manifest components to Manifest data class.

---

src/main/kotlin/com/autonomousapps/tasks/AdviceAggregateReportTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/295.

Safe-cast to ProjectDependency. Resolves issue 295.

---

settings.gradle.kts
src/main/kotlin/com/autonomousapps/advice/Advice.kt
src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceAggregateReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindClassesTask.kt

Partially resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/300.

Fix NPE and notice antlr dependencies.

---

src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/LocateDependenciesTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/300.
TODO: add a functional test.

Issue 300. General algorithm for ignoring dependencies on not-well-known configurations.

---

src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AntlrSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AntlrProject.groovy
src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindNativeLibsTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt
src/main/kotlin/com/autonomousapps/tasks/LocateDependenciesTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/AndroidSubproject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/BuildScript.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
testkit/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
testkit/src/main/kotlin/com/autonomousapps/kit/RootProject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Subproject.kt

Also fixes a bug in the recently-merged functionality.

Added a test to verify new interesting/boring location duality.

---

src/functionalTest/groovy/com/autonomousapps/DependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/FirebaseProject.groovy
src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/305.

Issue 305. Firebase is now part of a dependency bundle by default.

---

src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
src/functionalTest/groovy/com/autonomousapps/DependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/LintJarSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/LintJarProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/TimberProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/AnalyzedJar.kt
src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/KtFile.kt
src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePluginFactory.kt
src/main/kotlin/com/autonomousapps/internal/artifactViews.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/303

Don't recommend removing lint-only jars

---

src/main/kotlin/com/autonomousapps/tasks/DependencyGraphTask.kt

In one small test project, this resulted in a 99.9999% improvement.

Optimized GraphBuilder. Don't visit same node more than once.

---

settings.gradle.kts
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/Flags.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt

Resolve https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/321.

New system property to configure clearing of assemble artifacts. Use forUseAtConfigurationTime().

---

src/functionalTest/groovy/com/autonomousapps/android/AndroidKotlinInlineSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/CoreKtxSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/OtherAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AdviceFilterProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidKotlinInlineProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/TestSourceProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/ConstantsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/RedundantPluginsProject.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/AnotherCompileOnlyProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/CompileOnlyTestProject.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/tasks/BuildHealthTask.kt

1. On the class itself
2. On any public member (method or field)
3. On a parameter of a public method.
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/296.

Annotations on or in public classes are part of the ABI. This includes:

---

src/functionalTest/groovy/com/autonomousapps/jvm/AbiAnnotationsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AbiGenericsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiAnnotationsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiGenericsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GenericsProject.groovy
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
src/main/kotlin/com/autonomousapps/internal/utils/regex.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/328.

Generic types can be part of the ABI.

---

gradle/wrapper/gradle-wrapper.properties
src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/AnalyzedJar.kt

Resolves build issue for https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/336.

Bump Gradle to 6.7.1 and update test matrix.

---

src/functionalTest/groovy/com/autonomousapps/android/OtherAndroidSpec.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/Flags.kt
src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/tasks/AnalyzeJarTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyGraphTask.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
src/main/kotlin/com/autonomousapps/tasks/ProjectHealthTask.kt

Not quite done yet because I still need to fix and then verify Android. tl;dr I was mis-identifying where transitively-used dependencies were coming from because I was using the runtime classpath instead of the compile classpath.

WIP. Fixing transitive-use identification.

---

src/functionalTest/groovy/com/autonomousapps/android/NoOpSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/NoOpProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/VariantProject.groovy
src/main/kotlin/com/autonomousapps/advice/Advice.kt
src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt
src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt
src/main/kotlin/com/autonomousapps/internal/utils/booleans.kt
src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceSubprojectAggregationTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Repository.kt

Addresses https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/340.
~WIP: still needs tests.~

Assume deps on variants of api or impl are correctly on that variant.

---

CHANGELOG.md
src/main/kotlin/com/autonomousapps/tasks/AdvicePrinterTask.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/318.

Don't duplicate section headers in advice-console.txt.

---

src/functionalTest/kotlin/com/autonomousapps/fixtures/KtxProject.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt

Remove deprecated functions ahead of 1.0.

---

CHANGELOG.md
src/functionalTest/groovy/com/autonomousapps/jvm/AbiAnnotationsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AbstractJvmSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiAnnotationsProject.groovy
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/372

Detect usage of type annotations, and consider for ABI analysis.

---

src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AbstractJvmSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/SimilarAdviceSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/SimilarAdviceProject.groovy
src/functionalTest/kotlin/com/autonomousapps/utils/DebugAware.kt
src/functionalTest/kotlin/com/autonomousapps/utils/runner.kt
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceSubprojectAggregationTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/386 (I hope).

Issue 386. Annotate project path as task input property.

---

src/functionalTest/groovy/com/autonomousapps/jvm/MinimalAdviceSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/MinimalAdviceProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/MinimalFailProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/exception/BuildHealthException.kt
src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
src/main/kotlin/com/autonomousapps/internal/advice/SeverityHandler.kt
src/main/kotlin/com/autonomousapps/tasks/AdviceSubprojectAggregationTask.kt
src/main/kotlin/com/autonomousapps/tasks/BuildHealthTask.kt
src/main/kotlin/com/autonomousapps/tasks/MinimalAdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/ProjectHealthTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/397.

Issue 397. Don't fail on strict mode issues when using non-strict mode.

---

build.gradle.kts
src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/DefaultVariantSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/DefaultVariantProject.groovy
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
src/main/kotlin/com/autonomousapps/tasks/classAnalysisTasks.kt
src/test/kotlin/com/autonomousapps/internal/ClassSetReaderTest.kt
src/test/kotlin/com/autonomousapps/internal/JarReaderTest.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/393.

Issue 393. Detect provenance of classes used in static nested classes.

---

src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/394.

Don't suggest changing runtimeOnly to implementation.

---

gradle/wrapper/gradle-wrapper.properties

Update of https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/414.

Gradle 6.9-bin

---

CHANGELOG.md
src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/TestDependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestDependenciesProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt
src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/tasks/AnalyzeJarTask.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
src/test/kotlin/com/autonomousapps/fixtures/SeattleShelterDbModule.kt
src/test/kotlin/com/autonomousapps/internal/JarAnalyzerTest.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/366

Test-compile-classpath support.

---

src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/AndroidTestDependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidTestDependenciesProject.groovy
src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/424 (WIP).

Transitive test dependencies suggested to be put on wrong configuration.

---

src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/AndroidTestDependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidTestDependenciesProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/452

Resolves issue 452. Handle missing file input when Android unit tests are disabled for a variant.

---

CHANGELOG.md
settings.gradle.kts
src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/AndroidTestDependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidTestDependenciesProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/graph/GraphMinimizer.kt
src/main/kotlin/com/autonomousapps/tasks/MinimalAdviceTask.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/453

Handle missing graph when plugin not applied to some project, and strict mode off.

---

CHANGELOG.md
settings.gradle.kts
src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/AndroidTestDependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidTestDependenciesProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/graph/GraphMinimizer.kt
src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
src/main/kotlin/com/autonomousapps/tasks/MinimalAdviceTask.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/454

Handle complex Processor.init() functions. We try/catch and hope for the best.

---

src/functionalTest/groovy/com/autonomousapps/jvm/AbiAnnotationsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AbiExceptionsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AbiGenericsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiExceptionsProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/395
They aren't technically, per the Java specification, but they are in dependency management terms.

Declared exceptions are part of the ABI.

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/kotlinMetadataVisibilities.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/408

Detect constants from kt files in Kotlin 1.5.

---

CHANGELOG.md
src/functionalTest/groovy/com/autonomousapps/jvm/GradlePluginSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GradlePluginProject.groovy
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/464

Filter out jars from the Gradle distribution.

---

CHANGELOG.md
src/main/kotlin/com/autonomousapps/graph/ShortestPath.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/463

Sometimes it's ok the node isn't in the graph.

---

src/main/kotlin/com/autonomousapps/internal/advice/AdvicePrinter.kt
src/main/kotlin/com/autonomousapps/tasks/AdvicePrinterTask.kt
src/main/kotlin/com/autonomousapps/tasks/BuildHealthTask.kt
src/main/kotlin/com/autonomousapps/tasks/ProjectHealthTask.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/381
Replacement for https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/402

Remove output on success.

---

src/functionalTest/groovy/com/autonomousapps/jvm/AbiSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiProject.groovy

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/433

Add spec demonstrating that private props on internal classes are not part of the ABI.

---

CHANGELOG.md
src/functionalTest/groovy/com/autonomousapps/android/NativeLibSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/ResSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AttrResProject.groovy
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/internal/utils/xml.kt
src/main/kotlin/com/autonomousapps/tasks/AndroidResToResAnalysisTask.kt
src/test/kotlin/com/autonomousapps/internal/utils/XmlParserTest.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/420
Test added. 
WIP:

Detect attr usages in res-by-res algo.

---

CHANGELOG.md
src/functionalTest/groovy/com/autonomousapps/android/OtherAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/PostProcessingSpec.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/476.

Task "advice$variant" renamed to "generateAdvice$variant".

---

src/functionalTest/groovy/com/autonomousapps/jvm/projects/RenamingProject.groovy
src/main/kotlin/com/autonomousapps/internal/advice/AdvicePrinter.kt
src/main/kotlin/com/autonomousapps/tasks/AbiAnalysisTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindAndroidLinters.kt
src/main/kotlin/com/autonomousapps/tasks/RedundantKaptAlertTask.kt
src/main/kotlin/com/autonomousapps/tasks/RedundantPluginAlertTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/481

Replace '- ' prefix with '  '.

---

build.gradle.kts
src/functionalTest/groovy/com/autonomousapps/android/DaggerSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DaggerProject.groovy
src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/479
~Still WIP, as this clearly warrants a regression test.~

Analyze Dagger's annotation processor.

---

src/functionalTest/groovy/com/autonomousapps/jvm/AbiInterfaceSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiInterfaceProject.groovy
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/ImportFinderTask.kt
src/main/kotlin/com/autonomousapps/tasks/InlineMemberExtractionTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/501.
Replaces https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/500.

Interfaces are used.

---

src/functionalTest/groovy/com/autonomousapps/android/ResSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidMenuProject.groovy
src/main/kotlin/com/autonomousapps/tasks/AndroidResToResAnalysisTask.kt

This is much more comprehensive than what came before, hopefully such that it will now capture all such usages.
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/513
~WIP: Needs a test before merging.~

Detect more res-by-res usages.

---

gradle/wrapper/gradle-wrapper.properties
src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/ResSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AttrResWithNullProject.groovy
src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
src/main/kotlin/com/autonomousapps/tasks/AndroidResToResAnalysisTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/531

Resolve issue 531. Check regex match before asserting not-null.

---

src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt

See also https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/552

Stop spamming console output with 'Using plugin v2'

---

src/functionalTest/groovy/com/autonomousapps/jvm/PostProcessingSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/PostProcessingProject3.groovy
src/main/kotlin/com/autonomousapps/AbstractExtension.kt
src/main/kotlin/com/autonomousapps/AbstractPostProcessingTask.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisSubExtension.kt
src/main/kotlin/com/autonomousapps/advice/BuildHealth.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
testkit/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/GradleProjectWriter.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Repository.kt

Also added test fixture support for buildSrc, which was necessary to test the feature properly.

Add v2 support for post-processing advice.

---

src/functionalTest/groovy/com/autonomousapps/jvm/TestDependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestDependenciesProject2.groovy
src/main/kotlin/com/autonomousapps/tasks/FindDeclarationsTask.kt
src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt

With inspiration from https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/553.

Don't suggest removing test dependencies when test analysis is disabled.

---

src/main/kotlin/com/autonomousapps/internal/asm.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/577.

Use ASM 9 capabilities.

---

src/functionalTest/groovy/com/autonomousapps/jvm/JvmSpec.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/RedundantJavaLibraryPluginProject.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/subplugin/RedundantPlugin.kt

Only fixing this regression for v2.

Don't report kotlin as unused when it is in fact used.

---

src/functionalTest/groovy/com/autonomousapps/jvm/IncludedBuildSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildProject.groovy
src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
src/main/kotlin/com/autonomousapps/model/PhysicalArtifact.kt
src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindAndroidLinters.kt
src/main/kotlin/com/autonomousapps/tasks/FindAndroidResTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindNativeLibsTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt
src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
src/main/kotlin/com/autonomousapps/tasks/ManifestComponentsExtractionTask.kt

Relates to https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/565

Report useful information for modules from included builds.

---

src/main/kotlin/com/autonomousapps/tasks/FindAndroidLinters.kt

Make FindAndroidLinters cacheable

---

src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt

Partially resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/597. However, this issue also suggests the need to add bundle support (etc) for annotation processors, since it seems like Hilt + Dagger would make a natural bundle.
Will also need an integration test. Awaiting minimal reproducer from https://github.com/wbervoets.

Improve support for annotation processor advice.

---

src/main/kotlin/com/autonomousapps/AbstractExtension.kt
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/internal/artifactViews.kt
src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt
src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
src/main/kotlin/com/autonomousapps/model/SourceSetKind.kt
src/main/kotlin/com/autonomousapps/model/intermediates/DependencyTraceReport.kt
src/main/kotlin/com/autonomousapps/model/intermediates/Reason.kt
src/main/kotlin/com/autonomousapps/model/intermediates/Usage.kt
src/main/kotlin/com/autonomousapps/model/intermediates/Variant.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/AbiAnalysisTask.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt
src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt

1. Needs some improvements to console formatting.
2. Needs tests.
3. Possibly needs more information a la the original impl.
To use:
```
./gradlew my:module:reason --id some:library:1.0
```
The version at the end is optional.

Re-implemented ReasonTask. Still a WIP:

---

src/functionalTest/groovy/com/autonomousapps/jvm/AbiExclusionsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiExclusionsProject.groovy
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/610.

Fix AbiHandler.excludeAnnotations.

---

src/functionalTest/groovy/com/autonomousapps/jvm/AbiGenericsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiGenericsProject.groovy
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/634.

Capture generic types in class signature.

---

src/functionalTest/groovy/com/autonomousapps/jvm/projects/GradleBuildSrcConventionMultiConfigProject.groovy
src/main/kotlin/com/autonomousapps/tasks/FilterAdviceTask.kt

Support (optional) dependency version in the exclusion identifier

---

src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmSourceSet.kt
src/main/kotlin/com/autonomousapps/model/declaration/Bucket.kt
src/main/kotlin/com/autonomousapps/model/declaration/Configurations.kt
src/main/kotlin/com/autonomousapps/model/declaration/Declaration.kt
src/main/kotlin/com/autonomousapps/model/declaration/SourceSetKind.kt
src/main/kotlin/com/autonomousapps/model/declaration/Variant.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindDeclarationsTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt
src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
src/test/groovy/com/autonomousapps/model/declaration/BucketSpec.groovy
src/test/groovy/com/autonomousapps/model/declaration/VariantSpec.groovy

Tightening up declaration-related classes.

---

src/functionalTest/groovy/com/autonomousapps/android/AndroidAssetsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidAssetsProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidKotlinInlineProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/KotlinStdlibProject.groovy
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmSourceSet.kt
src/main/kotlin/com/autonomousapps/internal/artifactViews.kt
src/main/kotlin/com/autonomousapps/model/Capability.kt
src/main/kotlin/com/autonomousapps/model/declaration/SourceSetKind.kt
src/main/kotlin/com/autonomousapps/model/intermediates/Reason.kt
src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindAndroidAssetProviders.kt
src/main/kotlin/com/autonomousapps/tasks/FindDeclarationsTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt
src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/AndroidBlock.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/657.

Detect Android assets.

---

CHANGELOG.md
src/functionalTest/groovy/com/autonomousapps/android/projects/AttrResProject.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/TransitiveAdviceAndroidProject.kt
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/model/Source.kt
src/main/kotlin/com/autonomousapps/tasks/XmlSourceExploderTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/664.

More aggressively find attr usages in resource files.

---

src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/354.

Analyze projects that have the org.gretty plugin applied.

---

src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/GroovySmokeSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GenericsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GradleBuildSrcConventionMultiConfigProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GroovySmokeProject.groovy
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmSourceSet.kt
src/main/kotlin/com/autonomousapps/model/ProjectVariant.kt
src/main/kotlin/com/autonomousapps/model/Source.kt
src/main/kotlin/com/autonomousapps/model/intermediates/consumer.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/CodeSourceExploderTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
testkit/src/main/kotlin/com/autonomousapps/kit/SourceType.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/364.

Analyze Groovy projects.

---

src/functionalTest/groovy/com/autonomousapps/jvm/ScalaSmokeSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/ScalaSmokeProject.groovy
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/Language.kt
src/main/kotlin/com/autonomousapps/model/ProjectVariant.kt
src/main/kotlin/com/autonomousapps/model/Source.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/CodeSourceExploderTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
testkit/src/main/kotlin/com/autonomousapps/kit/SourceType.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/399.

Analyze Scala projects.

---

src/functionalTest/groovy/com/autonomousapps/android/projects/AdviceFilterProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidAssetsProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DataBindingUsagesExclusionsProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/ExternalApplicationProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/ConstantsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/ConstantsProject.groovy
src/main/kotlin/com/autonomousapps/internal/JarExploder.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/687.

Nested constants

---

src/main/kotlin/com/autonomousapps/internal/BytecodeParsers.kt
src/main/kotlin/com/autonomousapps/internal/ClassNames.kt
src/main/kotlin/com/autonomousapps/internal/JarExploder.kt
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/model/KtFile.kt
src/main/kotlin/com/autonomousapps/model/intermediates/ExplodingJar.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt

See also https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/694.

Less aggressive

---

src/main/kotlin/com/autonomousapps/internal/ManifestParser.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePlugin.kt
src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePlugin4_2.kt
src/main/kotlin/com/autonomousapps/model/Capability.kt
src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt
src/main/kotlin/com/autonomousapps/tasks/ManifestComponentsExtractionTask.kt
src/main/kotlin/com/autonomousapps/tasks/XmlSourceExploderTask.kt
src/test/kotlin/com/autonomousapps/internal/ManifestParserTest.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/700.

Get Android namespace from DSL.

---

build.gradle.kts
buildSrc/build.gradle.kts
shadowed/antlr/build.gradle.kts

Let's start with some safe updates.

Update some dependencies.

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
gradle/libs.versions.toml
shadowed/antlr/build.gradle.kts

IDEA support has improved a lot since last time I tried this.
Built on https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/705

Use dependency catalog for some dependencies.

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
gradle/libs.versions.toml
src/test/kotlin/com/autonomousapps/extension/BehaviorTest.kt
src/test/kotlin/com/autonomousapps/extension/BundleHandlerTest.kt
src/test/kotlin/com/autonomousapps/model/AdviceTest.kt

TODO: build scan before and after, compare dependencies.

Push more deps to the catalog. Stop using vintage JUnit4.

---

build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts
src/main/kotlin/com/autonomousapps/internal/graph/Graphs.kt
src/main/kotlin/com/autonomousapps/model/ProjectVariant.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt

Was not accounting for the reality of multiple dependency graphs.

Fix Reason's shortest-path output.

---

build.gradle.kts
settings.gradle.kts
src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt

Attempting to resolve https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/667.

Update kotlinx-metadat-jvm to 0.4.2.

---

src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/SeverityOverlaySpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/SeverityOverlayProject.groovy
src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/409.

Project severity overrides global severity.

---

src/main/kotlin/com/autonomousapps/internal/asm.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/722.

Detect generic types from field signatures.

---

src/functionalTest/groovy/com/autonomousapps/jvm/AbiExclusionsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiExclusionsProject.groovy
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt

~TODO: should probably add a test.~ Done.

Consider 'invisible annotations' for purposes of ABI exclusions.

---

src/functionalTest/groovy/com/autonomousapps/android/ReasonSpec.groovy
src/functionalTest/kotlin/com/autonomousapps/utils/Colors.kt
src/main/kotlin/com/autonomousapps/internal/Bundles.kt
src/main/kotlin/com/autonomousapps/model/Capability.kt
src/main/kotlin/com/autonomousapps/model/intermediates/Reason.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt
src/test/kotlin/com/autonomousapps/internal/BundlesTest.kt
src/test/kotlin/com/autonomousapps/internal/graph/GraphsTest.kt
src/test/kotlin/com/autonomousapps/tasks/DeepThoughtTest.kt
src/test/kotlin/com/autonomousapps/test/utils.kt
src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt

Needs a bit more work, yet, but it's already more useful.

Make 'reason' a bit more useful.

---

src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/729.

Reason should know about the runtime classpath.

---

build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts
src/main/kotlin/com/autonomousapps/advice/PluginAdvice.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt
src/main/kotlin/com/autonomousapps/model/Advice.kt
src/main/kotlin/com/autonomousapps/model/BuildHealth.kt
src/main/kotlin/com/autonomousapps/model/Capability.kt
src/main/kotlin/com/autonomousapps/model/Coordinates.kt
src/main/kotlin/com/autonomousapps/model/Dependency.kt
src/main/kotlin/com/autonomousapps/model/KtFile.kt
src/main/kotlin/com/autonomousapps/model/ModuleAdvice.kt
src/main/kotlin/com/autonomousapps/model/PhysicalArtifact.kt
src/main/kotlin/com/autonomousapps/model/ProjectAdvice.kt
src/main/kotlin/com/autonomousapps/model/ProjectVariant.kt
src/main/kotlin/com/autonomousapps/model/Source.kt
src/main/kotlin/com/autonomousapps/model/declaration/Declaration.kt
src/main/kotlin/com/autonomousapps/model/declaration/Variant.kt
src/main/kotlin/com/autonomousapps/model/intermediates/AndroidScoreVariant.kt
src/main/kotlin/com/autonomousapps/model/intermediates/BundleTrace.kt
src/main/kotlin/com/autonomousapps/model/intermediates/DependencyTraceReport.kt
src/main/kotlin/com/autonomousapps/model/intermediates/Reason.kt
src/main/kotlin/com/autonomousapps/model/intermediates/Usage.kt
src/main/kotlin/com/autonomousapps/model/intermediates/consumer.kt
src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt

It didn't solve the problem it was intended to solve, and introduced new problems. Not worth fiddling with.
See also https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/673.

Revert usage of KSP.

---

src/main/kotlin/com/autonomousapps/internal/ManifestParser.kt
src/main/kotlin/com/autonomousapps/internal/parse/explodeAndroidResSource.kt
src/main/kotlin/com/autonomousapps/tasks/XmlSourceExploderTask.kt
src/test/groovy/com/autonomousapps/internal/parse/AndroidManifestParserTest.groovy

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/720.

Be more robust in the face of manifests without a package declaration.

---

src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/internal/artifactViews.kt
src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeDuplicateDependenciesTask.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeResolvedDependenciesTask.kt
src/main/kotlin/com/autonomousapps/tasks/PrintDuplicateDependenciesTask.kt
src/main/kotlin/com/autonomousapps/tasks/ResolveExternalDependenciesTask.kt

Also sorts the output for readability and consistency.

Only resolve external dependencies. More performant.

---

src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/769

Only check AGP version on root project.

---

src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/782

AnnotationNode#values can be null.

---

src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/780

Sometimes providerClasses is empty. Don't include those as service loader dependencies.

---

src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt

This will have to be a patch release.

Don't analyze test source when test analysis is disabled.

---

gradle/libs.versions.toml
shadowed/asm-relocated/build.gradle.kts

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/806

Use asm 9.4.

---

src/main/kotlin/com/autonomousapps/internal/JarExploder.kt
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/model/Coordinates.kt
src/main/kotlin/com/autonomousapps/services/InMemoryCache.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/FindInlineMembersTask.kt
src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt

Improve performance in several tasks.

---

src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiExclusionsProject.groovy
src/main/kotlin/com/autonomousapps/AbstractExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisSubExtension.kt

Support ABI filtering on project level

---

README.asciidoc

Feel free to just add to the readme without merging the PR and close.

adds May 2022 newsletter

---

src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt
src/main/kotlin/com/autonomousapps/tasks/ExplodeJarTask.kt
src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt

Use buffered writer when writing ExplodedJar to file

---

src/functionalTest/groovy/com/autonomousapps/android/IgnoredVariantSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/VariantSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AbstractVariantProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AllVariantsIgnoredProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AllVariantsProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DebugVariantIgnoredProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/ReleaseVariantIgnoredProject.groovy
src/main/kotlin/com/autonomousapps/Flags.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt

Fixes #519
Hi I saw someone tried to resolve this by #613 I think one flag will be enough

Add flag for ignoring android variants

---

src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt

Use buffered reading when reading files in SynthesizeDependenciesTask

---

src/functionalTest/groovy/com/autonomousapps/jvm/DoubleExclusionsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/DoubleExclusionsProject.groovy
src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt

Allow exclusions to be added more than once

---

shadowed/antlr/src/main/antlr/com/autonomousapps/internal/grammar/Simple.g4
shadowed/antlr/src/test/groovy/com/autonomousapps/SimpleSpec.groovy

Add support for parsing import aliases

---

gradle/libs.versions.toml
shadowed/antlr/build.gradle.kts

@ZacSweers this will update the plugin to use the changes from https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/862.

Use new version of shadowed antlr jar.

---

src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt

Test for 00ea30f which fixes #875

Test for 00ea30f which fixes #875

---

src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
src/test/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilderTest.kt

Change text to clarify missing entries

---

src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt

Remove unnecessary usage of afterEvaluate in RootPlugin.

---

build-logic/settings.gradle.kts
gradle/libs.versions.toml
sandbox-sample/build.gradle
sandbox-sample/sample-build-logic/settings.gradle
sandbox-sample/settings.gradle
settings.gradle.kts

I think the latter was already effectively accomplished for classpath reasons, but there was a confusing lagging version string that may have been ignored.

Update Kotlin to 1.9.0. Also gradle.plugin-publish to 1.1.0.

---

src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt

This is an edge case. I do not know how to reproduce it, hence there is no test added.
Fixes #913
See also https://github.com/gradle/gradle/pull/26016

Handle ResolvedDependencyResult.resolvedVariant == null

---

src/functionalTest/groovy/com/autonomousapps/jvm/JvmReasonSpec.groovy
src/main/kotlin/com/autonomousapps/internal/reason/DependencyAdviceExplainer.kt
src/main/kotlin/com/autonomousapps/internal/utils/coordinatesStrings.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt
src/test/kotlin/com/autonomousapps/internal/reason/DependencyAdviceExplainerTest.kt

Fix addressing a project by path in the reason '--id' argument

---

src/functionalTest/groovy/com/autonomousapps/jvm/CompileOnlyJarSpec.groovy
src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
src/main/kotlin/com/autonomousapps/model/GradleVariantIdentification.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/950.
See also https://github.com/gradle/gradle/pull/26317.

Sometimes Kotlin DSL contains epicycles.

---

src/functionalTest/groovy/com/autonomousapps/android/MixedSourceSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/MixedSourceProject.groovy
src/main/kotlin/com/autonomousapps/internal/JarExploder.kt
src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
testkit/src/main/kotlin/com/autonomousapps/kit/GradleProjectWriter.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Source.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/948
TODO:

Handle Gradle bug relating to mixed source sets in local project depencies.

---

src/functionalTest/groovy/com/autonomousapps/jvm/BundleSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/BundleProject2.groovy
src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
src/main/kotlin/com/autonomousapps/internal/Bundles.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/952

Failing test.

---

src/functionalTest/groovy/com/autonomousapps/jvm/CustomSourceSetSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/SourceSetFilteringProject.groovy
src/main/kotlin/com/autonomousapps/extension/Behavior.kt
src/main/kotlin/com/autonomousapps/extension/Issue.kt
src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
src/main/kotlin/com/autonomousapps/extension/ProjectIssueHandler.kt
src/main/kotlin/com/autonomousapps/extension/SourceSetsHandler.kt
src/main/kotlin/com/autonomousapps/internal/DependencyScope.kt
src/main/kotlin/com/autonomousapps/internal/advice/SeverityHandler.kt
src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
src/main/kotlin/com/autonomousapps/internal/utils/gradleProperties.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/FilterAdviceTask.kt
src/test/groovy/com/autonomousapps/internal/advice/SeverityHandlerSpec.groovy
src/test/kotlin/com/autonomousapps/extension/BehaviorTest.kt
src/test/kotlin/com/autonomousapps/extension/IssueHandlerTest.kt
src/test/kotlin/com/autonomousapps/internal/DependencyScopeTest.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/901

Allow custom severity and filtering by source set.

---

gradle/libs.versions.toml

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/965.

Use asm-relocated 9.6.0.0.

---

settings.gradle.kts

...to not get deprecation warnings from that plugin.

Update 'com.gradle.enterprise' to 3.15.1

---

src/functionalTest/groovy/com/autonomousapps/AbstractProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/GradleBuildSrcConventionMultiConfigSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/CompileOnlyJarProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GradleBuildSrcConventionMultiConfigProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildWithSubprojectsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/RewriteDependenciesProject.groovy
testkit/build.gradle.kts
testkit/src/main/kotlin/com/autonomousapps/kit/AndroidBlock.kt
testkit/src/main/kotlin/com/autonomousapps/kit/AndroidSubproject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/BuildScript.kt
testkit/src/main/kotlin/com/autonomousapps/kit/BuildscriptBlock.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependencies.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
testkit/src/main/kotlin/com/autonomousapps/kit/DependencyResolutionManagement.kt
testkit/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/GradleProjectWriter.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Plugins.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Repositories.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Repository.kt
testkit/src/main/kotlin/com/autonomousapps/kit/RootProject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/SettingsScript.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Subproject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/render/Element.kt
testkit/src/main/kotlin/com/autonomousapps/kit/render/Scribe.kt
testkit/src/test/kotlin/com/autonomousapps/kit/render/ScribeTest.kt

Some TODOs remain. And I think I should decouple the rendering from the classes themselves.

TestKit improvements.

---

src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidProjectWithKmpDependencies.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/FeatureVariantInSameProjectTestProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/FeatureVariantTestProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/SourceSetFilteringProject.groovy
testkit/src/main/kotlin/com/autonomousapps/kit/BuildScript.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Feature.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Java.kt
testkit/src/main/kotlin/com/autonomousapps/kit/JvmToolchain.kt
testkit/src/main/kotlin/com/autonomousapps/kit/Kotlin.kt
testkit/src/main/kotlin/com/autonomousapps/kit/SourceSet.kt
testkit/src/main/kotlin/com/autonomousapps/kit/SourceSets.kt
testkit/src/main/kotlin/com/autonomousapps/kit/render/Scribe.kt
testkit/src/test/kotlin/com/autonomousapps/kit/render/ScribeTest.kt

Revert first commit before merging.

Model Java, Kotlin, and sourceSets blocks.

---

src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt

It still -- amazingly, after all these years -- configures all tasks in the build when syncing.

Change how the Gradle 7.5 check works for improved Intellij support.

---

src/functionalTest/groovy/com/autonomousapps/jvm/projects/VersionCatalogProject.groovy
testkit/CHANGELOG.md
testkit/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
testkit/src/main/kotlin/com/autonomousapps/kit/gradle/GradleProperties.kt

1. More ergonomic methods on GradleProject and GradleProject.Builder
2. Simplifed gradle.properties.

Simplify testkit fixture-creation:

---

src/functionalTest/groovy/com/autonomousapps/android/AndroidKotlinInlineSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/DominanceTreeSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AdviceFilterProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidKotlinInlineProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidToJvmInlineProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DominanceTreeProject.groovy
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/Source.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/SourceType.kt

https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/987

Write test to validate issue 987, but test passes.

---

testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/PluginManagement.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Repository.kt
testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTest.kt

Also just redirect to Repositories.DEFAULT_PLUGINS.

Remove mavenLocal() from default repos for pluginManagement.

---

src/functionalTest/groovy/com/autonomousapps/AbstractProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/BundleSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AbstractAndroidProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/KmpAndroidProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/BundleSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/BundleKmpProject2.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestBundleProject.groovy
src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
src/main/kotlin/com/autonomousapps/internal/Bundles.kt
src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
src/main/kotlin/com/autonomousapps/model/Coordinates.kt
src/main/kotlin/com/autonomousapps/model/GradleVariantIdentification.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
src/main/kotlin/com/autonomousapps/visitor/GraphViewReader.kt
src/main/kotlin/com/autonomousapps/visitor/GraphViewVisitor.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/GradleProperties.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/AndroidBlock.kt
testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTest.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/963

Revert #919.

---

src/functionalTest/groovy/com/autonomousapps/AbstractProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/AnnotationProcessorSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/BundleSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/CouldBeAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AbstractAndroidProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/CouldBeAndroidProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AbiExclusionsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AbiGenericsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/BundleSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/CustomSourceSetSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/RedundantJvmPluginsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/VersionCatalogSpec.groovy

This behavior is now baked into the base test class.

Remove redundant flags in tests.

---

.github/workflows/pr.yml
.github/workflows/push.yml

https://github.com/gradle/gradle-build-action

chore: use gradle-build-action v3-prerelease.

---

.github/workflows/pr.yml

Documentation for future reference:
1. https://github.com/gradle/gradle-build-action
2. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
3. https://github.com/actions/github-script

chore: comment on PR with build scan if any step fails.

---

src/functionalTest/groovy/com/autonomousapps/android/ResSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/ResDuplicateAttrProject.groovy
src/functionalTest/kotlin/com/autonomousapps/kit/gradle/dependencies/Dependencies.kt
src/main/kotlin/com/autonomousapps/internal/parse/explodeAndroidResSource.kt
src/main/kotlin/com/autonomousapps/model/Source.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/980.

fix: don't suggest unnecessary dependency relating to Android res and new IDs.

---

src/functionalTest/groovy/com/autonomousapps/jvm/ApplicationSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/ApplicationProject.groovy

Should be somewhere else but I'm feeling lazy.

test: tiny test for gradle-testkit-truth.

---

src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidSources.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt

Looks like an AGP bug. A ticket will be filed later.
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1111.

fix: don't pass in android res (incl layouts) to XmlSourceExploderTask.

---

src/main/kotlin/com/autonomousapps/model/Coordinates.kt

If this does not cause any unexpected problems, it's a "simple" solution for https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/908.

Use a hash in file name for dependencies with capabilities

---

src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidSources.kt

Resolves https://issuetracker.google.com/issues/325307775

fix: try/catch to workaround AGP issue.

---

build.gradle.kts

chore: remove dagp exclusions.

---

src/main/kotlin/com/autonomousapps/internal/BytecodeParsers.kt
src/main/kotlin/com/autonomousapps/internal/ConstantPoolParser.kt

https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1150

fix: enhance logging (more) when ConstantPoolParser throws exception.

---

src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt

fix: Fix Windows file separator incompatibility

---

src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
src/main/kotlin/com/autonomousapps/tasks/FindDeclarationsTask.kt

fix: sort an input map for better reproducibility.

---

gradle/libs.versions.toml
src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt

closes https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1192 , I think.
Let me know if there is any other place to update.

update agp max version to 8.4.1

---

testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Dependency.kt

Probably warrants javadoc or improved API to handle common capabilities like platform and test-fixtures. Will do in a follow-up.

feat(testkit): expose capability overload on Dependency.

---

build.gradle.kts
src/main/kotlin/com/autonomousapps/internal/ConstantPoolParser.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1150

fix: handle constant pool tag 17 (CONSTANT_DYNAMIC).

---

src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt

Skip checking all potential usages as soon as a single one is discovered.
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1186

fix: improve performance of usesResByRes.

---

src/functionalTest/groovy/com/autonomousapps/android/ResSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/EmptyResFile.groovy
src/main/kotlin/com/autonomousapps/internal/parse/explodeAndroidResSource.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1211

fix: gracefully handle 'empty' Android res file.

---

src/functionalTest/groovy/com/autonomousapps/android/SettingsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/SettingsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/SettingsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/SettingsProject.groovy
src/functionalTest/kotlin/com/autonomousapps/kit/gradle/dependencies/Plugins.kt
src/main/kotlin/com/autonomousapps/BuildHealthPlugin.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/services/GlobalDslService.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1222

feat: helpful error message when KGP or AGP are missing from build classpath.

---

src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/JvmSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/RedundantJvmPluginsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/RedundantJvmPluginsProject.groovy
src/functionalTest/kotlin/com/autonomousapps/advice/truth/BuildHealthSubject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/RedundantJavaLibraryPluginProject.kt
src/functionalTest/kotlin/com/autonomousapps/fixtures/annotationProcessorProjects.kt
src/main/kotlin/com/autonomousapps/internal/advice/SeverityHandler.kt
src/main/kotlin/com/autonomousapps/model/PluginAdvice.kt
src/main/kotlin/com/autonomousapps/model/ProjectAdvice.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/DetectRedundantJvmPluginTask.kt
src/main/kotlin/com/autonomousapps/tasks/FilterAdviceTask.kt

with the rest of the public models.

feat: move PluginAdvice to the model package. 

---

README.asciidoc
src/functionalTest/groovy/com/autonomousapps/jvm/JvmSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/SubprojectSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/SubprojectProject.groovy
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisSubExtension.kt
src/main/kotlin/com/autonomousapps/Flags.kt
src/main/kotlin/com/autonomousapps/services/GlobalDslService.kt
src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt

I think we're almost ready for v2.0 with this.

feat: don't auto-fail build when autoapply flag is set to false.

---

src/main/kotlin/com/autonomousapps/BuildHealthPlugin.kt
src/main/kotlin/com/autonomousapps/internal/GradleVersions.kt
src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/GenerateBuildHealthTask.kt

1. fix: check Gradle version at least 8.8 when applying build-health plugin.
2. feat: check that buildHealth did something.

check Gradle version at least 8.8 when applying build-health plugin, and check buildHealth did something.

---

src/functionalTest/groovy/com/autonomousapps/jvm/FacadeSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/ClasspathConfusionProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/FacadeProject.groovy
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt

fix: consider dependency unused candidate if only capability is InferredCapability.

---

src/functionalTest/groovy/com/autonomousapps/jvm/projects/BundleProject.groovy
src/main/kotlin/com/autonomousapps/extension/BundleHandler.kt
src/main/kotlin/com/autonomousapps/services/GlobalDslService.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1134

fix: when setting bundle primary, also 'include' dependency.

---

src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
src/main/kotlin/com/autonomousapps/services/GlobalDslService.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1256

fix: include version catalog entries even when plugin not applied to root.

---

src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidThemeProject.groovy
src/main/kotlin/com/autonomousapps/internal/parse/explodeAndroidResSource.kt
src/main/kotlin/com/autonomousapps/model/Source.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1038
Replaces https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1146

fix: consistently replace '.' with '_' in Android res.

---

src/functionalTest/groovy/com/autonomousapps/jvm/AbiSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiImplementationProject.groovy
src/main/kotlin/com/autonomousapps/internal/asm.kt

Reproduces (but does not yet resolve) https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1215

test: reproduce issue 1215.

---

src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidToJvmInlineProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DataBindingUsagesExclusionsProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DataBindingWithExpressionsProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/KmpAndroidProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/KotlinTestJunitProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/ResProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/SettingsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AbiSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/CompileOnlySpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiExcludedSourceSetProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/BundleKmpProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/CompileOnlyProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/RedundantJvmPluginsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/SettingsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/TypealiasProject.groovy
src/main/kotlin/com/autonomousapps/internal/BytecodeParsers.kt
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/model/ProjectVariant.kt
src/main/kotlin/com/autonomousapps/model/Source.kt
src/main/kotlin/com/autonomousapps/model/intermediates/Reason.kt
src/main/kotlin/com/autonomousapps/model/intermediates/consumer.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/subplugin/RedundantJvmPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/AndroidScoreTask.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
src/main/kotlin/com/autonomousapps/tasks/SynthesizeProjectViewTask.kt

For now, just annotation vs not-annotation.
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1215

feat: start to add information about how a class is referenced in bytecode.

---

src/functionalTest/groovy/com/autonomousapps/jvm/AnnotationsImplementationSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AnnotationsCompileOnlyProject.groovy
src/main/kotlin/com/autonomousapps/internal/asm.kt

I do not think I will ever finish handling annotation-related issues.

fix: @Metadata's d2 array should typically be compileOnly.

---

src/functionalTest/groovy/com/autonomousapps/jvm/AnnotationsImplementationSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AnnotationsImplementationProject2.groovy
src/main/kotlin/com/autonomousapps/model/intermediates/Reason.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Feature.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Java.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Toolchain.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1290

fix: don't suggest removing runtime-required annotation libraries.

---

src/functionalTest/groovy/com/autonomousapps/jvm/GuavaCheckSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/GuavaProject.groovy
src/functionalTest/kotlin/com/autonomousapps/kit/gradle/dependencies/PluginProvider.kt
src/main/kotlin/com/autonomousapps/services/GlobalDslService.kt
src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1288

feat: check Guava is at minimum required version.

---

src/functionalTest/groovy/com/autonomousapps/android/projects/DataBindingUsagesExclusionsProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DataBindingWithExpressionsProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AnnotationsImplementationSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/CompileOnlySpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AnnotationByDelegateProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/CompileOnlyProject2.groovy
src/main/kotlin/com/autonomousapps/internal/BytecodeParsers.kt
src/main/kotlin/com/autonomousapps/internal/asm.kt

fix: differentiate visible from invisible annotations.

---

gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
testkit/gradle.properties
testkit/settings.gradle.kts

https://docs.gradle.org/8.11.1/release-notes.html

chore: build with Gradle 8.11.1.

---

build-logic/convention/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
src/main/kotlin/com/autonomousapps/internal/JarExploder.kt
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/kotlinMetadataVisibilities.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/kotlinVisibilities.kt
src/main/kotlin/com/autonomousapps/model/internal/KtFile.kt
src/main/kotlin/com/autonomousapps/tasks/FindKotlinMagicTask.kt

Can't use latest, because I'm still compiling against Kotlin 1.9.

fix: use stable kotlin-metadata 2.0.21.

---

src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/models.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1329.

fix: superClassName can be null (Object has no superclass).

---

gradle/libs.versions.toml
src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt

This updates the project to:
- AGP 8.8.0 (latest feature release).
- AGP 8.7.3 (latest bugfix release).

Update to AGP 8.8.0

---

src/main/kotlin/com/autonomousapps/internal/BytecodeParsers.kt
src/main/kotlin/com/autonomousapps/internal/utils/comparators.kt
src/main/kotlin/com/autonomousapps/model/internal/Capability.kt
src/main/kotlin/com/autonomousapps/model/internal/Source.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/consumer/ExplodingBytecode.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/producers.kt
src/main/kotlin/com/autonomousapps/tasks/AssetSourceExploderTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindAndroidResTask.kt
src/main/kotlin/com/autonomousapps/tasks/XmlSourceExploderTask.kt

Previously we were comparing only by coordinates and that may have been causing problems.

fix: dependency model classes (etc) are now fully Comparable.

---

src/functionalTest/groovy/com/autonomousapps/android/NativeLibSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/NativeLibProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/AppleSiliconSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/AppleSiliconProject.groovy
src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/artifactViews.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
src/main/kotlin/com/autonomousapps/tasks/FindNativeLibsTask.kt
src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt

fix: incorrect attribution of so files to Android deps.

feat: detect dependencies that provide dylibs for use on macOS.

---

src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt

This is a hack that will be reverted or improved very quickly, and should not be relied upon.

feat: add temporary flag to test opting out of superclass analysis.

---

src/main/kotlin/com/autonomousapps/AbstractExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
src/main/kotlin/com/autonomousapps/DependencyAnalysisSubExtension.kt
src/main/kotlin/com/autonomousapps/internal/advice/AdvicePrinter.kt
src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/GenerateBuildHealthTask.kt
src/main/kotlin/com/autonomousapps/tasks/GenerateProjectHealthReportTask.kt
src/main/kotlin/com/autonomousapps/tasks/RewriteTask.kt
src/test/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilderTest.kt
src/test/kotlin/com/autonomousapps/internal/parse/GroovyBuildScriptDependenciesRewriterTest.kt
src/test/kotlin/com/autonomousapps/internal/parse/KotlinBuildScriptDependenciesRewriterTest.kt

Replace https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1189.

feat: support typesafe project accessors with opt-in.

---

src/main/kotlin/com/autonomousapps/tasks/DiscoverClasspathDuplicationTask.kt

I was seeing a warning like this:
```
Warnings
Some of your classpaths have duplicate classes, which means the compile and runtime behavior can be sensitive to the classpath order.
Source set: main
\--- compile classpath
+--- org/jetbrains/kotlin/gradle/dsl/JvmTarget is provided by multiple dependencies: [org.jetbrains.kotlin:kotlin-gradle-plugin-api:2.1.20,
org.jetbrains.kotlin:kotlin-gradle-plugin-api:2.1.20]
+--- org/jetbrains/kotlin/gradle/dsl/JvmTarget$Companion is provided by multiple dependencies: [org.jetbrains.kotlin:kotlin-gradle-plugin-ap
i:2.1.20, org.jetbrains.kotlin:kotlin-gradle-plugin-api:2.1.20]
+--- org/jetbrains/kotlin/gradle/dsl/KotlinJvmCompilerOptions is provided by multiple dependencies: [org.jetbrains.kotlin:kotlin-gradle-plug
in-api:2.1.20, …
```

fix: duplicate class warning doesn't warn about multiple dependencies with same GAV.

---

testkit/gradle-testkit-plugin/CHANGELOG.md
testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/GradleTestKitSupportExtension.kt

https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1422

feat(testkit): update default support lib version to 0.18.

---

testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/artifacts/BuildArtifact.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/artifacts/FileCollector.kt

I'd like to add more utilities here to, e.g., get all the entries out of jar files, parse XML, etc.

feat(testkit): add facility for getting file artifacts from build result.

---

src/functionalTest/groovy/com/autonomousapps/jvm/ConstantsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/ConstantsProject.groovy
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1430.

fix: detect constants defined in Kotlin companion objects.

---

src/functionalTest/groovy/com/autonomousapps/android/ResSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidThemeActivityProject.groovy
src/functionalTest/kotlin/com/autonomousapps/fixtures/LeakCanaryProject.kt
src/main/kotlin/com/autonomousapps/internal/ManifestParser.kt
src/main/kotlin/com/autonomousapps/internal/parse/explodeAndroidResSource.kt
src/main/kotlin/com/autonomousapps/model/Advice.kt
src/main/kotlin/com/autonomousapps/tasks/XmlSourceExploderTask.kt
src/test/kotlin/com/autonomousapps/internal/ManifestParserTest.kt

feat: add support for Activity `theme` in `AndroidManifest.xml`

---

src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/utils/regex.kt

TODO: cleanup TODOs and temporary code. Add a test.

fix: detect class references in the base package.

---

.github/workflows/test.yml

https://github.com/gradle/actions/blob/main/docs/setup-gradle.md

feat: replace custom BuildScan comments with official solution

---

gradle/libs.versions.toml
src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/AllDependenciesSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/DominanceTreeSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/DuplicateDependencyVersionsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/LeakCanarySpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/LeakCanaryProject.groovy
src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidSources.kt
src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
src/main/kotlin/com/autonomousapps/model/internal/ProjectVariant.kt
src/main/kotlin/com/autonomousapps/model/internal/Source.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/Reason.kt
src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
src/main/kotlin/com/autonomousapps/tasks/SynthesizeProjectViewTask.kt
src/main/kotlin/com/autonomousapps/tasks/XmlSourceExploderTask.kt
src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
src/test/kotlin/com/autonomousapps/internal/reason/DependencyAdviceExplainerTest.kt

feat: Android merged manifests are now treated as runtime requirements.  feat: update min support AGP version to 8.3.

---

build-logic/convention/src/main/kotlin/com/autonomousapps/convention/BaseConventionPlugin.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1476.

test: disable signing when running :functionalTest.

---

build-logic/convention/build.gradle.kts

Inspired by https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1354.

chore: cleanup build script.

---

src/functionalTest/groovy/com/autonomousapps/jvm/ConstantsSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/ConstantsProject.groovy
src/main/kotlin/com/autonomousapps/internal/BytecodeParsers.kt
src/main/kotlin/com/autonomousapps/internal/asm.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
src/main/kotlin/com/autonomousapps/internal/models.kt
src/main/kotlin/com/autonomousapps/model/internal/AccessFlags.kt
src/main/kotlin/com/autonomousapps/model/internal/Capability.kt
src/main/kotlin/com/autonomousapps/model/internal/ProjectVariant.kt
src/main/kotlin/com/autonomousapps/model/internal/Source.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/ExplodingJar.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/Reason.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/consumer/ExplodingBytecode.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/consumer/LdcConstant.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/consumer/MemberAccess.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/producer/BinaryClass.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/producer/Constant.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/producer/ExplodedJar.kt
src/main/kotlin/com/autonomousapps/model/internal/intermediates/producer/Member.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
src/main/kotlin/com/autonomousapps/tasks/SynthesizeProjectViewTask.kt
src/test/kotlin/com/autonomousapps/internal/reason/DependencyAdviceExplainerTest.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1504

fix: detect usage of more kinds of import, e.g. of inner classes.

---

.gitignore
api/api.txt
build-logic/convention/src/main/kotlin/com/autonomousapps/convention/tasks/metalava/CheckApiTask.kt
src/functionalTest/groovy/com/autonomousapps/AbstractProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/VariantSpec.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/AbstractVariantProject.groovy
src/functionalTest/groovy/com/autonomousapps/android/projects/DebugUsageProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/PomRelocationSpec.groovy
src/functionalTest/kotlin/com/autonomousapps/kit/gradle/dependencies/Plugins.kt
src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
src/main/kotlin/com/autonomousapps/internal/transform/StandardTransform.kt
src/main/kotlin/com/autonomousapps/internal/transform/UsageToConfigurationMapper.kt
src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
src/main/kotlin/com/autonomousapps/model/GradleVariantIdentification.kt
src/main/kotlin/com/autonomousapps/model/internal/declaration/Configurations.kt
src/main/kotlin/com/autonomousapps/model/source/SourceKind.kt
src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/android/AndroidManifest.kt

Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1473

fix: use Android flavors when appropriate.

---

testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/GradleTestKitSupportExtension.kt
testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/internal/Configurer.kt
testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/internal/arguments/IncludeBuildReposArgumentProvider.kt
testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/internal/arguments/RepoAndVersionArgumentProvider.kt

Should ought to improve relocatability.

feat(testkit): set system properties via lazy jvmArgumentProviders.

---

src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidFileMutationProject.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/FileMutationSpec.groovy
src/functionalTest/groovy/com/autonomousapps/jvm/projects/FileMutationProject.groovy
src/main/kotlin/com/autonomousapps/tasks/CodeSourceExploderTask.kt
testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/Source.kt

Follow-up to https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1534.

test: add jvm.FileMutationSpec to complement android.AndroidFileMutationSpec.

---

build-logic/convention/build.gradle.kts
build-logic/convention/src/main/kotlin/com/autonomousapps/convention/internal/kotlin/KotlinConfigurer.kt
build.gradle.kts
gradle.properties
graph-support/build.gradle.kts
testkit/build.gradle.kts
testkit/gradle-testkit-plugin/build.gradle.kts
testkit/gradle-testkit-support/build.gradle.kts
testkit/gradle.properties
variant-artifacts/build.gradle.kts

https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1537#issuecomment-3299483547

fix: remove kotlin-stdlib as default dep to ensure correct version.
