autonomousapps/dependency-analysis-gradle-plugin

- src/main/kotlin/com/autonomousapps/internal/ArtifactToComponentTransformer.kt
- src/main/kotlin/com/autonomousapps/internal/utils.kt
- src/main/kotlin/com/autonomousapps/tasks/DependencyReportTask.kt
I would like to do further refactors, and begin to extract classes that wrap the classes in `asm.kt` to facilitate unit testing.
I would also like to eventually make this task use the Worker API, but before I can do that I need to figure out what to do about my usage of `project.configurations.getByName(...)`, etc. Maybe that can be pulled back into the configuration phase, and the result given to the task as an input?
> Extracted class from DependencyReportTask.

- src/main/kotlin/com/autonomousapps/internal/ArtifactToComponentTransformer.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
- src/main/kotlin/com/autonomousapps/tasks/InlineMemberExtractionTask.kt
- src/test/kotlin/com/autonomousapps/fixtures/SeattleShelterDbModule.kt
The next thing would be to make `Artifact.file` a `val`, but at least one test relies on it being a `var`, so we can make that change later on.
> Simplified model classes.

- CHANGELOG.md
- src/functionalTest/groovy/com/autonomousapps/AndroidTests.groovy
- src/functionalTest/kotlin/com/autonomousapps/fixtures/LeakCanaryProject.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/dependencyAnalysis.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
- src/main/kotlin/com/autonomousapps/internal/outputDirectories.kt
- src/main/kotlin/com/autonomousapps/tasks/AndroidResAnalysisTask.kt
- src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ManifestPackageExtractionTask.kt
- src/test/kotlin/com/autonomousapps/tasks/MisusedDependencyDetectorTest.kt
Service is sufficient to capture LeakCanary, and ContentProvider makes sense on principle. Trying not to be too aggressive.
Fixes https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/80
> Fixed: don't consider an android lib unused if it contributes a ContentProvider or Service

- PUBLISHING.asciidoc
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/AnalyzedJar.kt
- src/main/kotlin/com/autonomousapps/internal/ArtifactToComponentTransformer.kt
- src/main/kotlin/com/autonomousapps/internal/instrumentation/InstrumentationBuildService.kt
- src/main/kotlin/com/autonomousapps/services/InMemoryCache.kt
- src/main/kotlin/com/autonomousapps/tasks/ConstantUsageDetectionTask.kt
- src/main/kotlin/com/autonomousapps/tasks/DependencyReportTask.kt
- src/main/kotlin/com/autonomousapps/tasks/InlineMemberExtractionTask.kt
- src/test/kotlin/com/autonomousapps/InlineMemberFinderTest.kt
- src/test/kotlin/com/autonomousapps/internal/ArtifactToComponentTransformerTest.kt
- src/test/kotlin/com/autonomousapps/stubs/StubInMemoryCache.kt
- src/test/kotlin/com/autonomousapps/stubs/StubProperty.kt
This saves us from repeatedly re-analyzing the same bytecode.
> Improve performance by using a simple in-memory cache.

- CHANGELOG.md
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
- src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GeneralUsageDetectionTask.kt
- src/test/kotlin/com/autonomousapps/tasks/MisusedDependencyDetectorTest.kt
This heuristic actually seems correct and I see no need to complicate it. If an import statement says com.mycompany.foo.Bar, and a dependency has class com.mycompany.foo.Bar, how else to interpret the situation than that the producer uses the consumer?
> Renamed 'generic' stuff as 'general' to reflect what it actually does

- CHANGELOG.md
- src/functionalTest/groovy/com/autonomousapps/fixtures/jvm/Dependency.groovy
- src/functionalTest/groovy/com/autonomousapps/fixtures/jvm/Plugin.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/ApplicationSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/ApplicationProject.groovy
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
Resolves an issue that leads to runtime crash when both are applied and the plugin tries to add duplicate tasks.
> Trying to account for use of both the application and kotlin-jvm plugins

- CHANGELOG.md
- src/functionalTest/groovy/com/autonomousapps/fixtures/jvm/Dependency.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/SecurityProviderSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/SecurityProviderProject.groovy
- src/functionalTest/kotlin/com/autonomousapps/jvm/projects/SecurityProviderAdvice.kt
- src/main/kotlin/com/autonomousapps/internal/AnalyzedJar.kt
- src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
Addresses https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/153.
Ideally I will extend this solution to only ignore security providers when there's something on the classpath that actually tries to use one. There is already prior art for this, but the bytecode analysis that would do it is currently only performed on the project's code itself, not any of its dependencies. Introducing that might have negative performance implications, potentially not worth the small (is it?) benefit.
> Don't suggest removing security providers.

- build.gradle.kts
- src/functionalTest/groovy/com/autonomousapps/jvm/AbiExclusionsSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiExclusionsProject.groovy
- src/functionalTest/kotlin/com/autonomousapps/jvm/projects/AbiExclusionsAdvice.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
- src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
- src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
- src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
- src/main/kotlin/com/autonomousapps/tasks/AbiAnalysisTask.kt
- src/test/kotlin/com/autonomousapps/internal/AbiDependenciesTest.kt
This is intended to resolve #48 by adding a new API to extensions for `abi` handling and `exclusions` configuration.
The API in practice looks like this:
```kotlin
abi {
exclusions {
// Convenience helpers
ignoreSubPackage("internal")
ignoreInternalPackages()
ignoreGeneratedCode()
// Raw, regexp-based APIs
excludeAnnotations(".*\\.Generated")
excludeClasses(".*\\.internal\\..*")
}
}
```
I've left toe-holds in for directory based parsing (i.e. `build/`), but that will take more work as the current code looks only at class files and not where they originated from.
No tests yet as I want to put this up for review of the design before moving further.
> Support ABI exclusions

- src/functionalTest/groovy/com/autonomousapps/android/AdviceSpec.groovy
- src/functionalTest/kotlin/com/autonomousapps/fixtures/adviceTestProject.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/advice/Advice.kt
- src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
- src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FailOrWarnTask.kt
- src/test/kotlin/com/autonomousapps/internal/ConsoleReportTest.kt
Solves issue #172.
Ignore/warn/fails on errors related to dependencies that "could be compile only".
Adds an issue handler method to the DSL:
```
onAdvisedCompileOnly {
fail(<"foo">)
}
```
@autonomousapps , we need to update the wiki after this is merged.
> Filter for compile only dependencies via DSL

- CHANGELOG.md
- src/functionalTest/groovy/com/autonomousapps/jvm/LombokSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/PostProcessingSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiExclusionsProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/ConstantsProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/LombokProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/SecurityProviderProject.groovy
- src/main/kotlin/com/autonomousapps/internal/utils/regex.kt
- src/main/kotlin/com/autonomousapps/tasks/FindUnusedProcsTask.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/188. (except that it doesn't handle when the jar task has been disabled)
> Support star imports for finding annotation processors.

- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
AGP 4.0+ allow test variant filtering.
See example here:
https://github.com/android/gradle-recipes/blob/master/BuildSrc/testVariantFilteringOnBuildType/buildSrc/src/main/kotlin/CustomPlugin.kt
The plugin should support that some modules might have a null variant.
> Solves #207

- src/main/kotlin/com/autonomousapps/internal/ConstantPoolParser.kt
This improves compatibility for projects using Java 8 when using a JDK 9 version of the plugin.
> Cast ByteBuffer to Buffer to resolve what looks like a JDK bug.

- CHANGELOG.md
- build.gradle.kts
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/asm.kt
- src/main/kotlin/com/autonomousapps/tasks/LocateDependenciesTask.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/244.
It's still not great, since the task is no longer cacheable and uses the `Project` instance directly, but at least it's lazy now. I will follow-up later and see if I can change how this task does its work.
> Move some heavy configuration to a task action.

- CHANGELOG.md
- CONTRIBUTING.asciidoc
- build.gradle.kts
- gradle.properties
- src/functionalTest/groovy/com/autonomousapps/jvm/AssembleArchivesSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/SimpleJvmLibraryProject.groovy
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
This ensure it doesn't get hooked into the assemble task, which is bad news.
Finally resolves the issue whereby users executing `assemble` (or some variants thereof) would also have this plugin's artifacts assembled, which was normally not desirable. Per Gradle, this current automagic behavior is deprecated and will eventually be removed (along with the old "archives" configuration).
> Remove aggregate advice from archives configuration.

- CHANGELOG.md
- src/main/kotlin/com/autonomousapps/tasks/LocateDependenciesTask.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/255.
> Resolves issue 255. LocateDependenciesTask cannot declare all its inputs.

- src/functionalTest/groovy/com/autonomousapps/android/AndroidKotlinInlineSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidKotlinInlineProject.groovy
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/173
The cause was failing to parse Kotlin source in src/main/kotlin in Android projects that failed to use android.sourceSets..., instead wrongly using sourceSets....
> Resolves Issue 173, misses inline member usage.

- src/functionalTest/groovy/com/autonomousapps/DependenciesSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/KotlinStdlibProject.groovy
- src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
- src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
Improve support for Kotlin 1.4, wherein the plugin adds the stdlib by default.
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/262.
> Kotlin stdlib should be a dependency bundle by default.

- src/main/kotlin/com/autonomousapps/AbstractAbiPostProcessingTask.kt
- src/main/kotlin/com/autonomousapps/AbstractExtension.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
Intended to resolve https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/237.
This can be tested as follows:
```groovy
// Create a new task with type `AbstractPostProcessingTask`
def postDebug = tasks.register("postProcessDebug", AbstractAbiPostProcessingTask) {
doLast {
String abiDump = abiDump()
println(abiDump)
}
}
dependencyAnalysis {
registerAbiPostProcessingTask(postDebug, "debug")
}
```
and then `./gradlew lib:postProcess`. You should see your ABI dump get printed to console.
This is very similar to the existing facility to consume the advice output, described in the wiki [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Post-processing).
> Initial pass at making the variant ABI more accessible.

- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/advice/ReasonableDependency.kt
- src/main/kotlin/com/autonomousapps/graph/Node.kt
- src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt
- src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/metaInf.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
- src/main/kotlin/com/autonomousapps/tasks/AnalyzeJarTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindAndroidLinters.kt
- src/main/kotlin/com/autonomousapps/tasks/FindClassesTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindNativeLibsTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt
- src/test/kotlin/com/autonomousapps/internal/JarAnalyzerTest.kt
Partially resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/303.
So far this PR only 
1. Finds android libraries that include lint jars
2. Includes this information in certain reports (including `reason`)
It does not yet use it for computing advice. To do that, I think I will need to also check if the library is either
1. being used in some other capacity (for example Timber, which is a library + a lint jar)
2. is _only_ a lint jar (such as the little robots RxLintRegistry)
> Find lint jars. (But don't do much with them, yet.)

- antlr/build.gradle.kts
- antlr/src/main/antlr/com/autonomousapps/internal/grammar/Simple.g4
- antlr/src/test/groovy/com/autonomousapps/SimpleSpec.groovy
- build.gradle.kts
- src/main/kotlin/com/autonomousapps/AbstractAbiPostProcessingTask.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/advice/Ripple.kt
- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
- src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
- src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
- src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
- src/main/kotlin/com/autonomousapps/tasks/AdviceAggregateReportTask.kt
- src/main/kotlin/com/autonomousapps/tasks/AdviceSubprojectAggregationTask.kt
- src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GeneralUsageDetectionTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ImportFinderTask.kt
Fixes two bugs:
1. Failed parsing of Kotlin source for import statements when that file includes `@file:JvmName("...")`
2. linking of dependencies to their used-transitive dependencies was over-zealous thanks to the inclusion of java platforms.
> Improved parsing of Kotlin source. Don't include Java Platforms in transitive relations.

- CHANGELOG.md
- antlr/src/main/antlr/com/autonomousapps/internal/grammar/Simple.g4
- antlr/src/test/groovy/com/autonomousapps/SimpleSpec.groovy
- build.gradle.kts
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/advice/Ripple.kt
- src/main/kotlin/com/autonomousapps/internal/advice/RippleWriter.kt
- src/main/kotlin/com/autonomousapps/internal/utils/colors.kt
- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
- src/main/kotlin/com/autonomousapps/tasks/AdviceAggregateReportTask.kt
- src/main/kotlin/com/autonomousapps/tasks/BuildHealthTask.kt
- src/main/kotlin/com/autonomousapps/tasks/RipplesTask.kt
* Run `./gradlew ripples` to see a report of expected downstream (dependent) impacts from upstream (dependency) changes.
* `LocateDependenciesTask` no longer resolves dependencies
* Updated Kotlin source parsing for imports
* First pass at colorizing console output
> Added :ripples task and also fixed a few bugs.

- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/Flags.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
Use like
```
./gradlew buildHealth -Ddependency.analysis.test.analysis=false
```
or
```
systemProp.dependency.analysis.test.analysis=false
```
The default value is `true`.
> Add system property to configure enabling of test-related code analysis.

- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/graph/DependencyGraph.kt
- src/main/kotlin/com/autonomousapps/graph/DepthFirstSearch.kt
- src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt
- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
- src/main/kotlin/com/autonomousapps/internal/advice/RippleWriter.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
- src/main/kotlin/com/autonomousapps/tasks/DependencyGraphAggregationTask.kt
- src/main/kotlin/com/autonomousapps/tasks/LocateDependenciesTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ProjectGraphAggregationTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ProjectGraphTask.kt
Adds a couple new features, similar to `:ripples`, to enable the user to see potential downstream impacts from upstream changes.
```
./gradlew :projectGraphReport
```
will generate two graphviz DOT files
1. The project dependency graph (not including any external dependencies)
2. The reverse project dependency graph ("A depends on B, so if I change B, A might be impacted")
and
```
./gradlew :projectGraphReport --id :my-project
```
will generate three graphviz DOT files. The two above, and additionally
3. The reverse project dependency graph anchored on `:my-project` (i.e. a subgraph showing potential impacts from changing `:my-project`)
> Add tasks to view project dependency graphs.

- CHANGELOG.md
- build.gradle.kts
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/333
> Don't use an enforced platform for the Kotlin BOM.

- CHANGELOG.md
- src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/350.
> Changed path-sensitivity to ABSOLUTE to account for artifacts in a transform directory.

- .github/workflows/pr.yml
- .github/workflows/push.yml
- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/DataBindingSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/advice/filter/DataBindingFilter.kt
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
Getting a weird failure locally (maybe related to building with Java 11?). https://scans.gradle.com/s/wlyny2evw26uk/tests
Maybe this fixes it? https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio
Looking at the failures, I only see it with AGP 3.x. The AGP 7.x failure is a legit failure due to a new databinding-related dependency.
> Test against AGP 7.0.0-alpha05.

- src/main/kotlin/com/autonomousapps/tasks/DependencyGraphAllProjects.kt
- src/main/kotlin/com/autonomousapps/tasks/ReasonAggregationTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt
`@Option` arguments weren't considered as inputs for tasks. This resulted in wrong up-to-date or cache results.
> Fix inputs for Option arguments

- src/functionalTest/groovy/com/autonomousapps/JvmSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/RedundantPluginsSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/RedundantPluginsProject.groovy
- src/functionalTest/kotlin/com/autonomousapps/fixtures/RedundantJavaLibraryPluginProject.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/RedundantPluginSubPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/RedundantKaptAlertTask.kt
- src/main/kotlin/com/autonomousapps/tasks/RedundantPluginAlertTask.kt
Don't emit warning about redundant plugins when behavior is set to ignore.
> Don't report java-library plugin as redundant.

- src/main/kotlin/com/autonomousapps/internal/ManifestParser.kt
- src/main/kotlin/com/autonomousapps/tasks/ManifestPackageExtractionTask.kt
- src/test/kotlin/com/autonomousapps/internal/ManifestParserTest.kt
```
> ./gradlew :lib:projectHealth
Execution failed for task ':lib:extractPackageNameFromManifestDebug':
java.lang.IllegalStateException: it.attributes.getNamedItem(component.attrName) must not be null
at com.autonomousapps.tasks.ManifestPackageExtractionTask.componentNames(ManifestPackageExtractionTask.kt:86)
at com.autonomousapps.tasks.ManifestPackageExtractionTask.extractManifestComponents(ManifestPackageExtractionTask.kt:66)
at com.autonomousapps.tasks.ManifestPackageExtractionTask.action(ManifestPackageExtractionTask.kt:43)
```
It happens for manifests with `provider` inside [queries](https://developer.android.com/guide/topics/manifest/queries-element#provider). It has other attributes.
Example: [com.yandex.android:mobmetricalib:3.20.1](https://repo1.maven.org/maven2/com/yandex/androi …
> Fix Android manifest parsing in case of queries node

- src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt
- src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt
- src/main/kotlin/com/autonomousapps/tasks/InlineMemberExtractionTask.kt
I'm currently working in a repo that leaks non-jar file types (i.e. xml) onto
the classpath. The other filetypes causes the dependency analysis tool to
throw ZipExceptions since the tool tries to open each file as a ZipFile.
Test:
1. Import dependency analysis into my repo
2. Run "./gradlew buildHealth" -> fails
3. Build dependency analysis tool with these changes (make snapshot)
4. Import snapshot of dependency analysis into my repo
5. Run "./gradlew buildHealth" -> passes and shows valid results
> Java bytecode analysis will filter to analyze only jar files

- src/functionalTest/groovy/com/autonomousapps/jvm/TestDependenciesSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestBundleProject.groovy
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/advice/ComponentWithTransitives.kt
- src/main/kotlin/com/autonomousapps/advice/TransitiveDependency.kt
- src/main/kotlin/com/autonomousapps/graph/ShortestPath.kt
- src/main/kotlin/com/autonomousapps/internal/JarAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
- src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt
- src/main/kotlin/com/autonomousapps/internal/advice/filter/DependencyBundleFilter.kt
- src/main/kotlin/com/autonomousapps/internal/advice/filter/FilterSpec.kt
- src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
- src/main/kotlin/com/autonomousapps/tasks/AdvicePerVariantTask.kt
- src/main/kotlin/com/autonomousapps/tasks/DependencyGraphPerVariant.kt
- src/main/kotlin/com/autonomousapps/tasks/DependencyMisuseTask.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
* Now supports test dependencies.
* Now supports multiple hops between dependencies in a bundle.
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/425.
> Resolves bundle issue.

- src/functionalTest/groovy/com/autonomousapps/android/AnnotationProcessorSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/KaptProject.groovy
- src/main/kotlin/com/autonomousapps/advice/PluginAdvice.kt
- src/main/kotlin/com/autonomousapps/tasks/RedundantKaptAlertTask.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/427.
> Can now ignore a 'redundant plugin' error.

- src/main/kotlin/com/autonomousapps/internal/classReferenceParsers.kt
- src/main/kotlin/com/autonomousapps/tasks/CreateVariantFiles.kt
File.separator instead of / so that file system paths are processed properly when running builds on windows. Actually the problem was covered by TestDependenciesSpec "unused test dependencies are reported" already: Running it on windows failed before doing this change. With the change it now passes.
> Fixes issue 529.

- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
> Add project path as input to disambiguate.

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/BuildMetricsSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/TestDependenciesSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/CustomSourceSetSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/JvmSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/MinimalAdviceSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/PostProcessingSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/RenamingSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/RippleSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/SimilarAdviceSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/TestDependenciesSpec.groovy
- src/functionalTest/kotlin/com/autonomousapps/fixtures/ProjectDirProvider.kt
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
My plan is to release 1.0.0-rc01 with a new default and the ability to use the old model if desired. Then I will immediately release 1.0.0-rc02 that _deletes_ the old model completely; this will be the only change between rc01 and rc02. RCs after that will include bug fixes, only for the new model. No new features planned, but I will consider reintroducing removed features before the final 1.0.0 release.
> Set default to new model. Prepare initial 1.0.0 release candidate.

- src/functionalTest/groovy/com/autonomousapps/jvm/IncludedBuildSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildProject.groovy
- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
- src/main/kotlin/com/autonomousapps/model/Coordinates.kt
- src/main/kotlin/com/autonomousapps/model/Dependency.kt
- src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/GradleProjectWriter.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/SettingsScript.kt
Resolves crash associated with https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/565, but it doesn't handle any analysis across the composite boundary.
> TestKit now supports included builds. Don't crash in presence of included build. 

- src/functionalTest/groovy/com/autonomousapps/jvm/GradleBuildSrcConventionMultiConfigSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/GradleBuildSrcConventionMultiConfigProject.groovy
- src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/SourceType.kt
To share configuration across multiple sub projects we make use of the Gradle convention plugins. We have a few common dependency which we want to ignore for unused/configuration advices but sometimes this is also needed per-subproject level. We ran into the following on RC3:
```
Caused by: org.gradle.api.GradleException: You must configure this project either at the root or the project level, not both
Caused by: org.gradle.api.InvalidUserDataException: Cannot add a ProjectIssueHandler with name ':BLA:BLA' as a ProjectIssueHandler with that name already exists.
```
> Allow common configuration through build logic and override on project level

- src/functionalTest/groovy/com/autonomousapps/jvm/GraphViewCacheSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/GraphViewCacheProject.groovy
- src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
Don't use @Classpath, use @InputFiles.
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/612
> Fix build cache issue with GraphViewTask.

- src/functionalTest/groovy/com/autonomousapps/android/AnnotationProcessorSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/KaptProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/RedundantJvmPluginsSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/advice/SeverityHandler.kt
- src/main/kotlin/com/autonomousapps/tasks/FilterAdviceTask.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/462.
> onAny should also control onRedundantPlugins behavior.

- src/functionalTest/groovy/com/autonomousapps/android/LintJarSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/LintJarProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/ServiceLoaderProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/SecurityProviderProject.groovy
- src/functionalTest/kotlin/com/autonomousapps/fixtures/LeakCanaryProject.kt
- src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
- src/main/kotlin/com/autonomousapps/model/Advice.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
If an advice was computed to change a declaration from 'implementation'/'api' to 'runtimeOnly', this is indeed correct
information. The dependency is *not* required at compile time. But it *might* be required at runtime.
It is not possible for this plugin to make a clear statement about if it is actually needed at runtime. When getting such an advice, the user might also remove the dependency completely. The 'reason' feature will give more insight on why the dependency *might* be needed at runtime. The following cases are covered:
- Contains Service Loader declarations
- Contains Security Provider declarations
- Contains Content Provider or Service declarations (Android)
- Contains Android linters (Lint-Registry entry)
Fixes #387
> Give advice to change to runtimeOnly where appropriate

- src/functionalTest/groovy/com/autonomousapps/android/AdviceSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AdviceFilterProject.groovy
- src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/FilterAdviceTask.kt
Allows customising the handling of 'runtimeOnly' advices like this:
```
dependencyAnalysis {
issues {
project(':lib_android') {
onRuntimeOnly {
severity 'fail'
exclude 'nl.littlerobots.rxlint:rxlint'
}
}
}
}
```
Follow up to #646.
> Support 'onRuntimeOnly' in issue handler

- src/functionalTest/groovy/com/autonomousapps/jvm/CustomSourceSetSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/FeatureVariantTestProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IntegrationTestProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestFixturesTestProject.groovy
- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Configurations.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Declaration.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Variant.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindDeclarationsTask.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- src/test/groovy/com/autonomousapps/model/declaration/VariantSpec.groovy
- src/test/kotlin/com/autonomousapps/internal/configuration/ConfigurationsTest.kt
- src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
The plugin currently may give wrong advices for source sets that are not yet supported (see #451 and #298).
This PR:
- Adds tests to show the issues.
- Ignores the unsupported cases for now so that users can use these Gradle features and still use this plugin to analyse the dependencies of the source sets that are supported right now.
Problematic cases are:
The plugin produces advices (often wrong) for source sets that are not
yet supported. For example:
```
testFixturesApi("org.apache.commons:commons-collections4:4.4")
extraFeatureApi("org.apache.commons:commons-collections4:4.4")
```
The plugin may produce wrong advices by ignoring the 'requires capabilities' part of dependencies like this:
```
testImplementation(testFixtures(project(':proj')))
api(project(':proj')) { capabilities { …
```
> Ignore dependencies for and to unsupported sourceSets/variants

- src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
- src/main/kotlin/com/autonomousapps/tasks/AbiAnalysisTask.kt
This is in symmetry with other places where files are filtered by 'endsWith(".class")'. Without this, the plugin may attempt to analyses 'module-info.class' files of your own projects leading to an NPE.
> Filter out 'module-info.class' files in all places

- src/functionalTest/groovy/com/autonomousapps/jvm/CompileOnlyJarSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/WarTestProject.groovy
- src/main/kotlin/com/autonomousapps/model/declaration/Bucket.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Configurations.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
Similar to #651, the goal of this to avoid **wrong advices** to be reported rather than fully supporting what could be possible here (a follow up could be #648). The test in this PR shows an example where the plugin right now suggests moving dependencies aways from "compileOnlyApi" or "providedCompile".
From the perspective of this plugin right now, dependencies defined as 'compileOnlyApi' or 'providedCompile' should be treated the same as 'compileOnly'. Which is, there are no advices produced for them.
Some context on 'providedCompile':
The configuration is added by the 'war' Gradle core plugin if applied. This configuration exists for years already. If it would be introduced today, it would probably be called 'providedApi'. It has the same behaviour as the 'api' configuration, but with …
> Put 'compileOnlyApi' and 'providedCompile' into the COMPILE_ONLY bucket

- src/functionalTest/groovy/com/autonomousapps/jvm/BundleSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/BundleProject.groovy
- src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
- src/main/kotlin/com/autonomousapps/internal/Bundles.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
- src/test/kotlin/com/autonomousapps/internal/BundlesTest.kt
- src/test/kotlin/com/autonomousapps/test/utils.kt
- src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/662.
> Support a primary entry point for bundles.

- src/main/kotlin/com/autonomousapps/tasks/BuildHealthTask.kt
Terminal UIs often only linkify paths if there's a trailing space, so this should help avoid these not linking otherwise
> Add a trailing space for path linkifying

- build.gradle.kts
- src/main/kotlin/com/autonomousapps/advice/PluginAdvice.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
- src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt
- src/main/kotlin/com/autonomousapps/model/Advice.kt
- src/main/kotlin/com/autonomousapps/model/BuildHealth.kt
- src/main/kotlin/com/autonomousapps/model/Capability.kt
- src/main/kotlin/com/autonomousapps/model/Coordinates.kt
- src/main/kotlin/com/autonomousapps/model/Dependency.kt
- src/main/kotlin/com/autonomousapps/model/KtFile.kt
- src/main/kotlin/com/autonomousapps/model/PhysicalArtifact.kt
- src/main/kotlin/com/autonomousapps/model/ProjectAdvice.kt
- src/main/kotlin/com/autonomousapps/model/ProjectVariant.kt
- src/main/kotlin/com/autonomousapps/model/Source.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Bucket.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Declaration.kt
- src/main/kotlin/com/autonomousapps/model/declaration/SourceSetKind.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Variant.kt
- src/main/kotlin/com/autonomousapps/model/intermediates/DependencyTraceReport.kt
- src/main/kotlin/com/autonomousapps/model/intermediates/Reason.kt
- src/main/kotlin/com/autonomousapps/model/intermediates/Usage.kt
- src/main/kotlin/com/autonomousapps/model/intermediates/consumer.kt
- src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt
Faster runtime performance plus it should resolve #667 along the way.
Couldn't use moshi-ir due to the low kotlin version here (it only supports Kotlin 1.6+) and lucked out that the first stable version of KSP happened to be the version of Kotlin this uses.
> Use code gen for moshi adapters instead of reflection

- src/functionalTest/groovy/com/autonomousapps/jvm/BundleSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/BundleKmpProject.groovy
- src/main/kotlin/com/autonomousapps/internal/Bundles.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/659.
> Treat KMP modules as implicit bundles.

- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/ConfigurationCacheSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/GradleVersions.kt
- src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GenerateBuildHealthTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
This will prevent users' builds from breaking when they use configuration caching.
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/306
I will consider supporting configuration cache sometime after Gradle 7.5 is GA.
> Specifically opt out of configuration cache support.

- src/main/kotlin/com/autonomousapps/internal/JarExploder.kt
See: 
- https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/688#discussion_r887805355
- https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/688#discussion_r888365942
> Use the same (unique) key when writing and reading to/from inMemoryCache

- src/functionalTest/groovy/com/autonomousapps/jvm/ComponentWithMultipleArtifactsSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/FeatureVariantTestProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/JarTransformingProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/MultipleJarsProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestFixturesTestProject.groovy
- src/main/kotlin/com/autonomousapps/model/Dependency.kt
- src/main/kotlin/com/autonomousapps/model/PhysicalArtifact.kt
- src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
- testkit/build.gradle.kts
In Gradle, one component - i.e. one logical component identified by GA coordinates or Gradle project path - can have multiple Jars. So far, the plugin would silently ignore all Jars except for the first it finds. With this fix, all Jars are considered part of the component during the analysis.
This used to work in older versions; tested with 0.71.0
> Support Components with multiple Jar files

- src/functionalTest/groovy/com/autonomousapps/jvm/BundleSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/BundleKmpProject2.groovy
- src/main/kotlin/com/autonomousapps/internal/Bundles.kt
- src/main/kotlin/com/autonomousapps/model/Coordinates.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/701.
Not yet resolved: output of `reason` still appears nonsensical. It needs to be enhanced with more knowledge about the results of bundle rule resolution.
> Detect KMP usages more vigorously.

- src/main/kotlin/com/autonomousapps/internal/BytecodeParsers.kt
- src/main/kotlin/com/autonomousapps/internal/ManifestParser.kt
- src/test/kotlin/com/autonomousapps/internal/ManifestParserTest.kt
Mitigates https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/720.
> Wrap manifest parsing exception in stronger exception type.

- src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
- src/main/kotlin/com/autonomousapps/model/Source.kt
- src/main/kotlin/com/autonomousapps/tasks/XmlSourceExploderTask.kt
- src/test/kotlin/com/autonomousapps/internal/utils/XmlParserTest.kt
Associating to a map was clobbering a lot of key-value pairs that all had the same key ('name' for example).
As a follow-up, I need to figure out how to declare that some res usages make a dependency `api` vs `implementation`.
> Detect more Android res usages.

- src/main/kotlin/com/autonomousapps/internal/advice/SeverityHandler.kt
- src/main/kotlin/com/autonomousapps/model/ModuleAdvice.kt
- src/test/groovy/com/autonomousapps/internal/advice/SeverityHandlerSpec.groovy
This will prevent the plugin crashing when the console report is empty and severity is set to 'fail' for module health.
Resolves https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/766.
> Consider moduleAdvice empty if none of it is actionable.

- src/main/kotlin/com/autonomousapps/internal/utils/regex.kt
- src/test/kotlin/com/autonomousapps/internal/utils/RegexKtTest.kt
If an annotation references multiple types they are not correctly exposed as part of a module's public ABI. This is because we filter for an annotation values to only include a single `Type`. However annotations may have a value of type `ArrayList<*>` which can contain references to other classes.
This patch updates the `List<AnnotationNode>?.annotationTypes()` method to correctly handle the above scenario and adds some unit tests for it.
> Fixes #763

- CHANGELOG.md
- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AndroidTestSourceSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/ReasonSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidKotlinInlineProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidMenuProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidTestDependenciesProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidTestSourceProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/ArbitraryFileProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AttrResProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AttrResWithNullProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/DaggerProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/DrawableFileProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/TestDependenciesProject.groovy
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/reason/DependencyAdviceExplainer.kt
- src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Bucket.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Configurations.kt
- src/main/kotlin/com/autonomousapps/model/declaration/SourceSetKind.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Variant.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- src/test/kotlin/com/autonomousapps/internal/configuration/ConfigurationsTest.kt
- src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/AndroidSubproject.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/GradleProjectWriter.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
Relates to https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/411.
> Add support for analyzing androidTest source sets.

- src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/IncludedBuildSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildWithSubprojectsProject.groovy
- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
- src/main/kotlin/com/autonomousapps/model/Coordinates.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/GradleProjectWriter.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/Subproject.kt
This PR adds test coverage and fixes two issues with included builds:
1. The requested version is irrelevant if resolved to an included build (sub)project. The analysis also needs to ignore it. Otherwise, it won't be able to connect the computed dependency information correctly to the declared dependencies.
2. If a build is included, inside that build the projects often still depend on each other using `project("...")` dependencies. This was not working.
See also commit messages and comments in code for more details.
Before the fix, if you would run the example that's part of the new test, you would have three files for the same dependency, where two of them were empty:
(The empty files were cause by the "fallback for pom-only dependencies" in `SynthesizeDependenciesWorkAction`)
> Fix issues with included builds

- src/functionalTest/groovy/com/autonomousapps/jvm/TestDuplicatedDependenciesSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/DuplicatedDependenciesProject.groovy
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
If there are two declarations to the same component with different scopes, e.g.
```
dependencies {
runtimeOnly("org.apache.commons:commons-collections4:4.4")
implementation("org.apache.commons:commons-collections4:4.4")
}
```
the analysis discarded one of them by using 'find' instead of 'filter' in StandardTransform.kt. This can lead to a wrong recommendation. In the example provided in the test, the plugin recommended to remove the 'implementation' dependency.
A related feature could be that the plugin also detects the duplication, and recommends to remove the unneeded declaration - in this case `runtimeOnly("...")`. Doing this, would be an additional analysis imo, as the plugin would need to check how the different configurations relate. And maybe this is also not wanted in all cases. …
> Duplicated declaration does not lead to wrong analysis result

- src/functionalTest/groovy/com/autonomousapps/jvm/projects/JavaModulesProject.groovy
- src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
Although you cannot see this in the Kotlin code, this (coming out of ASM) can be `null`.
Sorry for this follow up, I was tricked by being in Kotlin, not even thinking about that this can be `null`. 😐 
Follow up to #800
> Fix NPE in asmUtil.exportedPackages()

- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
The usage of 'findByName' and 'flatMap' cause the objects in the SourceSetContainer and its dependencies to be eagerly created.
Fixes #815.
> Prevent eager task creation during configuration time

- README.asciidoc
> Use syntax that's Groovy & Kotlin-compatible

- gradle/libs.versions.toml
This supports reading Kotlin 1.8 and 1.9 metadata. The current version only goes until 1.7 and on our branch to update to Kotlin 1.8.0 we are seeing that dependency analysis does not find usages of Kotlin constants or extension methods anymore.
For it to work I also needed to update Kotlin itself.
Full changelog
https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/ChangeLog.md
> bump kotlinx-metadata-jvm to 0.5.0

- src/functionalTest/groovy/com/autonomousapps/jvm/CustomSourceSetSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/FeatureVariantTestProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IntegrationTestProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestFixturesTestProject.groovy
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Configurations.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Declaration.kt
- src/main/kotlin/com/autonomousapps/model/declaration/SourceSetKind.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Variant.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- src/test/groovy/com/autonomousapps/model/declaration/VariantSpec.groovy
- src/test/kotlin/com/autonomousapps/internal/configuration/ConfigurationsTest.kt
This adds analyzing dependencies **FROM** other source sets (which are not `main` or `test`) in standard Gradle 'java-library' and 'application' projects.
For example: `testFixturesImplementation(...)` or `integrationTestImplementation(...)`
This partially addresses #298 and #451, in particular the first item I listed in this comment: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/298#issuecomment-1346159435
It is solved as follows:
- All source sets registered in the `SourceSetContainer` are marked as supported for 'java-library' and 'application' projects.
- For each source set, we check if it can have an ABI by checking if the `api...` configuration was created. This happens, if you define a Feature Variant on top of a source set.
- There is a new …
> Analyze dependencies of all source sets in standard JVM projects

- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
Still not testing against 8.0+.
See also https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/802.
> Bump tested AGP versions.

- README.asciidoc
The badges on the top of the readme point to the images which are shown, which is not useful for the users. This PR replaces the links to point to actually useful URLs, where more details can be found.
> Fix badge links to point to actual things

- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
```
> Configure project :
The Dependency Analysis plugin is only known to work with versions of AGP between 4.2.2 and 7.4.1. You are using 7.4.2. Proceed at your own risk.
```
> Bump AGP minor 7.4.1 to 7.4.2

- src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestFixturesTestProject.groovy
- src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
...for example 'exclude(...)'.
It is now 'vararg' and fills a Set (instead of a List).
Follow up to: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/882#issuecomment-1516575385
> Make 'ignoreSourceSet(...)' DSL construct consistent with others

- src/main/kotlin/com/autonomousapps/services/InMemoryCache.kt
When using composite builds, currently there is one cache per build in the build tree. So for example if one build is composed of 300 included builds, there will be 300 caches – which makes the memory consumption explode.
Heap dump analysis from such a build:
> Use one InMemoryCache for all builds in a composite build tree

- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ExplodeJarTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
Their purpose was during early development to simplify some common debugging tasks. They have outlived their usefulness.
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/903
> Remove pretty-printed files.

- src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/IncludedBuildSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildWithAnnotationProcessorProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildWithSubprojectsProject.groovy
- src/main/kotlin/com/autonomousapps/internal/Bundles.kt
- src/main/kotlin/com/autonomousapps/internal/graph/GraphViewBuilder.kt
- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
- src/main/kotlin/com/autonomousapps/model/Coordinates.kt
- src/main/kotlin/com/autonomousapps/model/GradleVariantIdentification.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeDominatorTreeTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeProjectViewTask.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- src/test/kotlin/com/autonomousapps/internal/BundlesTest.kt
- src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt
There is a bug that leads to wrong/inconsistent advices if included builds are involved. I first thought this is probably an easy fix, but then discovered a more fundamental problem with the _included builds_ handling and went down that rabbit hole.
The assumption at the moment is that if a 'project path' matches the 'identity path', the dependency is not in an included build.
This is in:
[`gradleStrings.ResolvedArtifactResult.toCoordinates()`](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt#L66)
While this works in the case where we do not use included builds (much), it is generally wrong. There can also be references to other projects inside other included builds. And, more …
> Consistently use IncludedBuildCoordinates to refer to other projects

- src/functionalTest/groovy/com/autonomousapps/jvm/NestedProjectsSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/NestedSubprojectsProject.groovy
Because by default, the 'group' is derived from the project path, the identity differs even if if GA from the IncludeBuildCoordinates is used as identity.
Confirms that there is no problem here after the changes from #916.
See:
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/pull/916#discussion_r1244109793
> Add test: nested projects with same name have different identities

- src/functionalTest/groovy/com/autonomousapps/jvm/InMemoryCacheSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IncludedBuildWithDivergingPluginClasspathsProject.groovy
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/services/InMemoryCache.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt
Follow up to #914 
Users can run into https://github.com/gradle/gradle/issues/17559 is the plugin is loaded with different classloaders in different builds. In these cases we now keep the old behavior of having separate caches for separate builds.
There is now a test checking the two different cases.
> Only share InMemoryCache across builds if the same classloader was used to load the plugin

- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/Flags.kt
This adds a new property to control the compatibility warning log. There are three levels: `NONE`, `DEBUG`, `WARN`, `ERROR`. These correspond to their logger visibilities.
```properties
dependency.analysis.compatibility=NONE
```
Resolves #801
> Add gradle property to disable compatibility mismatch

- CHANGELOG.md
- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
I had some test failures running this locally that looked like flakes (failed running all of `functionalTest` but pass when running individually in IDE), lets see if CI agrees
> Test against AGP 8.1.0 as latest supported stable version

- src/main/kotlin/com/autonomousapps/internal/GradleVersions.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
Right now, 8.3 prints a deprecation warning for the getName() method: https://scans.gradle.com/s/s23mexkai26qe/deprecations
> Use BuildIdentifier.getBuildPath() starting with Gradle 8.2

- build.gradle.kts
- gradle/libs.versions.toml
- graph-support/build.gradle.kts
- graph-support/src/main/kotlin/com/autonomousapps/graph/Graphs.kt
- settings.gradle.kts
- shadowed/antlr/build.gradle.kts
- shadowed/asm-relocated/build.gradle.kts
- src/functionalTest/groovy/com/autonomousapps/jvm/CustomSourceSetSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/CustomTestSourceSetProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/FeatureVariantTestProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/IntegrationTestProject.groovy
- src/main/kotlin/com/autonomousapps/internal/GradleVersions.kt
- src/main/kotlin/com/autonomousapps/internal/utils/multimaps.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Variant.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt
- testkit/src/main/kotlin/com/autonomousapps/kit/BuildScript.kt
Addresses multiple issues around sourceset-based analysis:
1. When analyzing the `test` sourceset, don't suggest "upgrading" dependency declarations to something `api`-like. That sourceset has no ABI; it is not published.
2. When analyzing sourcesets that extend other sourcesets, don't redundantly suggest adding dependencies to them that are inherited from their upstream sourcesets.
> Fix issues with sourceset-based analysis.

- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
For example, in Gradle plugin projects.
> Fix lingering parity issue when both java-library and kotlin-jvm plugins are applied.

- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/IncludedBuildSpec.groovy
- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/internal/GradleVersions.kt
- src/main/kotlin/com/autonomousapps/internal/graph/CCGraphViewBuilder.kt
- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
- src/main/kotlin/com/autonomousapps/tasks/ResolveExternalDependenciesTask.kt
This is a first step towards making the rest of the plugin compatible.
Replaces https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/867.
> ResolveExternalDependencies is configuration-cache compatible.

- sandbox-sample/build.gradle
- src/functionalTest/groovy/com/autonomousapps/android/DependenciesSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/BundleProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/RewriteDependenciesProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/TestBundleProject.groovy
- src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
- src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
Resolves #891. Open to suggestions on the name, this felt the most semantically similar
> Deprecate dependencyAnalysis.dependencies for structure

- src/main/kotlin/com/autonomousapps/Flags.kt
This became obsolete in Gradle 7.4 and is now deprecated. Minimal version of this plugin is 7.5 so it can be removed.
> Remove forUseAtConfigurationTime()

- src/main/kotlin/com/autonomousapps/extension/Issue.kt
This pr adds a version of `exclude` that accepts version catalog dependencies. I didn't see any existing tests for this file, but let me know if there is somewhere I should be adding tests for this.
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/946
> Add exclude method for version catalog dependencies

- src/functionalTest/groovy/com/autonomousapps/jvm/IncludedBuildSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
Follow up to #949
I totally missed these other usages. They did not show up in the builds I tested with and I forgot about them. Sorry for updating this inconsistently in #949.
> Use BuildIdentifier.getBuildPath() starting with Gradle 8.2 (second PR)

- testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/GradleTestKitPlugin.kt
- testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/PublishingConfigurator.kt
I still want to make the test name configurable, although it seems (annoyingly) like it might require `afterEvaluate`, and I would like some kind of improved support for included builds.
> Cleanup / simplify.

- build-logic/convention/src/main/kotlin/nexus/NexusPublishTask.kt
Intellij IDEA configures all tasks when syncing the IDE, which is insane in 2023. Is this the dark ages?
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1015
> Move credentials null-check to task action.

- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
Been meaning to do this for ages. These are not declared dependencies, they're the exploded jars from the full compile classpath, direct and transitive.
> Rename all-declared-dependencies to exploded-jars.json.

- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
Sometimes (from KGP? Not sure) FindDeclarationsTask discovers flat dependencies that are:
1. () -> Any?
2. property 'destinationDirectory'
Basically they're properties that point to directories on the filesystem. They're not interesting for dependency analysis. So, skip them.
> Filter out weird flat dependencies.

- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/FindInlineMembersTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GenerateBuildHealthTask.kt
#1035
This happened when updating to kotlinx-metadata-jvm v0.7.0, which appears to have fixed a bug and become more strict. Not entirely clear on the root cause, so for now we just catch and log.
> Catch exception when analyzing Kotlin files for inline members.

- src/functionalTest/groovy/com/autonomousapps/jvm/AbiExclusionsSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiExcludedSourceSetProject.groovy
- src/main/kotlin/com/autonomousapps/extension/AbiHandler.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/BuildScript.kt
e.g.,
```
dependencyAnalysis {
abi {
exclusions {
excludeSourceSets('customSourceSet', 'another')
}
}
}
```
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1026
> Users can exclude source sets from ABI analysis.

- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/BuildResultSubject.kt
Right now when a test doesn't pass you get an output like this one:
```
Caused by: value of                : buildResult.task(:proj:compileJava2)
expected to have a value: FAILED
but was                 : null
buildResult was         : org.gradle.testkit.runner.internal.FeatureCheckBuildResult@1d75e7af
at [[Reflective call: 4 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
... 1 more
```
With this change we get outputs like this one that give more information:
```
Caused by: value of:
buildResult.task(:proj:compileJava2)
expected to have a value:
FAILED
but was:
null
buildResult was:
Calculating task graph as no cached configuration is available for tasks: proj:assemble
> Task :proj:processResources NO-SOURCE
> Task :proj:compileJava
> Task :proj:classes
> Task :proj:jar
> Task …
```
> Improve actual output on testkit-truth

- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Dependency.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Feature.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Plugin.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Repositories.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Repository.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/SettingsScript.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/SourceSet.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/AndroidBlock.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/CompileOptions.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/DefaultConfig.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/render/MethodOrAssignment.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/render/Scribe.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/render/text.kt
- testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTestGroovy.kt
- testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTestKotlin.kt
This isn't how I'd like the final implementation to look, but it unblocks Kotlin DSL usage and demonstrates concrete usages. We can try to push the implementation details into Scribe etc later.
> feat(testkit-support): support DslKind.KOTLIN.

- settings.gradle.kts
- shadowed/README.asciidoc
- shadowed/antlr/build.gradle.kts
- shadowed/asm-relocated/build.gradle.kts
The reason why I would like to have this working is that currently you can't use the plugin via:
```
pluginManagement {
includedBuild("/path/to/dependency-analysis-android-gradle-plugin")
}
```
Because the moment it becomes an included build, the composite build dependency substitution starts working and then the 'shadowed' components are used from source - which does not work without this change.
> Use the 'shadowed' subprojects from source

- src/functionalTest/groovy/com/autonomousapps/jvm/AssembleArchivesSpec.groovy
- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/BuildResultSubject.kt
Close #1068
This PR changes a bit the idea behind `BuildResultSubject.task`. It doesn't return a `BuildTaskSubject` with an `actual == null` anymore. Now BuildResultSubject.task fails if the task doesn't exist with a better error message.
Before:
```
Caused by: value of:
buildResult.task(:proj:compileJava2)
expected to have a value:
FAILED
but was:
null
buildResult was:
Calculating task graph as no cached configuration is available for tasks: proj:assemble
> Task :proj:processResources NO-SOURCE
> Task :proj:compileJava
> Task :proj:classes
> Task :proj:jar
> Task :proj:assemble
BUILD SUCCESSFUL in 2s
2 actionable tasks: 2 executed
Configuration cache entry stored.
```
After:
```
Caused by: value of:
buildResult.getTasks()
expected to contain:
:proj:compileJava2
but was: …
```
> Improve truth tasks

- gradle/libs.versions.toml
- src/functionalTest/groovy/com/autonomousapps/AbstractProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/DuplicateDependencyVersionsSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/IgnoredVariantSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AbstractVariantProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/DataBindingUsagesExclusionsProject.groovy
- src/main/kotlin/com/autonomousapps/Flags.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidSources.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidVariant.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/JvmSourceSet.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/Language.kt
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
- src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePlugin.kt
- src/main/kotlin/com/autonomousapps/internal/android/AndroidGradlePlugin4_2.kt
- src/main/kotlin/com/autonomousapps/model/ModuleAdvice.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/XmlSourceExploderTask.kt
Ahead of migrating to non-deprecated APIs.
TODO:
> feat: migrate to new, non-deprecated AGP APIs. Min AGP version now 8.0.

- src/functionalTest/groovy/com/autonomousapps/jvm/JavaToolchainSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/JavaToolchainProject.groovy
Big heads up:
1. I did not run many tests and I even saw a failure. Not sure if I had something setup wrong or what.
2. The test I added here *passes* even when I had 9.2 in use so I know it's not working. That said, when pulling from maven local the snapshot version I no longer see the error on my project so I know this fixes it (but could cause other problems).
I will look into running the full suite (and even the quick suite) soon, but this is just something quick and dirty so show the proof of concept.
For what it is worth, [here is my project](https://github.com/JacksonBailey/wheel/blob/3337502695e10c85efe31551340ab9b9584aea1a/build.gradle.kts#L3-L12) where the fix is shown in use. It's not really anything to look at but if you'd like to clone it and try you can. The `buildHealth` …
> Use asm unshadowed and upgrade to 9.4

- src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
- src/functionalTest/groovy/com/autonomousapps/AdviceStrategy.groovy
- testkit/gradle-testkit-support/build.gradle.kts
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/Subproject.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/artifacts/BuildArtifact.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/artifacts/FileType.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/BuildScript.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Dependency.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/internal/files.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/internal/strings.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/utils/files.kt
- testkit/gradle-testkit-truth/build.gradle.kts
- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/AbstractSubject.kt
- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/BuildResultSubject.kt
- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/BuildTaskSubject.kt
- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/TestKitTruth.kt
- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/artifact/BuildArtifactsSubject.kt
- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/artifact/JarSubject.kt
- testkit/gradle-testkit-truth/src/main/kotlin/com/autonomousapps/kit/truth/artifact/PathSubject.kt
- testkit/settings.gradle.kts
> feat: new APIs for artifact access from test fixtures.

- src/main/kotlin/com/autonomousapps/internal/Bundles.kt
- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Declaration.kt
- src/main/kotlin/com/autonomousapps/model/intermediates/Usage.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindDeclarationsTask.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt
If the main source set has a used dependency, and a custom source set has an unused transitive dependency, and these are at different versions, StandardTransform was advising the removal of the used dependency. Now we check that the usage is not undeclared before adding to the set of remove-advice.
> fix: handle disjoint classpaths.

- testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/GradleTestKitSupportExtension.kt
Calling it is idempotent so there's no point.
> fix: don't disallow changes on the disablePublication property.

- gradle/libs.versions.toml
- Bumps [gradle-script-grammar](https://github.com/autonomousapps/gradle-script-grammar) to `v0.3` to leverage [support for multiple closures](https://github.com/autonomousapps/gradle-script-grammar/pull/1)
Currently, if you run `fixDependencies` task and you have a dependency with the following syntax:
```groovy
dependencies {
implementation (libs.spotify.authSdk) {
artifact {
type = "aar"
}
}
api libs.androidx.constraintLayout
implementation projects.common.kotlinxCoroutines
implementation libs.kotlinx.coroutines.rx2
}
```
the dependencies will be rewritten as:
```groovy
dependencies {
implementation (libs.spotify.authSdk) {
artifact {
type = "aar"
}
api libs.androidx.constraintLayout
implementation projects.common.kotlinxCoroutines
implementation libs.kotlinx.coroutines.rx2
}
``` …
> Bump gradle-script-grammar to v0.3

- src/functionalTest/groovy/com/autonomousapps/android/projects/ArbitraryFileProject.groovy
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
Basic hypothesis is that tasks.whenTaskAdded eagerly realizes all tasks, which forces DAGP tasks to be configured too soon. Some of them have dependencies on AGP tasks that are registered later in the build lifecycle. This workaround uses afterEvaluate as a bandaid. Preferable would be using some Android- specific version of SourceSetContainer to get lazy access to compiled class files, instead of relying on tasks directly.
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1116
> fix: ugly workaround for issue 1116.

- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/GradleBuilder.kt
We don't want to encourage that. It makes debugging impossible. People can use runner() if they really need a custom env.
> fix: remove GradleBuilder methods that take an env.

- src/functionalTest/groovy/com/autonomousapps/jvm/AssembleArchivesSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/GradleVersions.kt
- src/main/kotlin/com/autonomousapps/internal/artifacts/configurations.kt
There's a bug in 8.4 where isInvisible=false has not been set, leading the inter-project publications to be added to the archives configuration and therefore being added to the assemble task.
See https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/908#issuecomment-1952162799
> fix: only use new configurations factories from Gradle 8.5.

- src/main/kotlin/com/autonomousapps/internal/utils/Files.kt
The file relativizing only worked properly on *nix systems.
On Windows even executing the tests failed with the code before this PR.
The PR makes the method work consistently on all operating systems.
> fix: make file relativizing work properly on Windows

- src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/AndroidScoreTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
- src/main/kotlin/com/autonomousapps/tasks/AssetSourceExploderTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ClassListExploderTask.kt
- src/main/kotlin/com/autonomousapps/tasks/CodeSourceExploderTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
- src/main/kotlin/com/autonomousapps/tasks/DetectRedundantJvmPluginTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ExplodeJarTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FilterAdviceTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindAndroidAssetProviders.kt
- src/main/kotlin/com/autonomousapps/tasks/FindAndroidLinters.kt
- src/main/kotlin/com/autonomousapps/tasks/FindAndroidResTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindDeclarationsTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindDeclaredProcsTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindInlineMembersTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindNativeLibsTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GenerateBuildHealthTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GenerateProjectHealthReportTask.kt
- src/main/kotlin/com/autonomousapps/tasks/GraphViewTask.kt
- src/main/kotlin/com/autonomousapps/tasks/ManifestComponentsExtractionTask.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeProjectViewTask.kt
This will make the output of the 'tasks' task more concise.
> chore: no group for 'internal' tasks.

- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/AbstractProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/NoAutoApplySpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/NoAutoApplyProject.groovy
- src/functionalTest/groovy/com/autonomousapps/utils/Strings.groovy
- src/main/kotlin/com/autonomousapps/internal/artifacts/Publisher.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/GenerateBuildHealthTask.kt
Don't mutate another project's dependencies.
There are two other IP issues:
1. Applying plugins on subprojects (but this can already be worked around with [this](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/wiki/Customizing-plugin-behavior#controlling-the-projects-on-which-the-plugin-is-applied)).
2. Access the root project's extensions container.
The second point will be the subject of a follow-up PR. I already know [conceptually how to do it](https://dev.to/autonomousapps/gradles-leaky-abstractions-declarativeish-shell-imperative-core-implementing-a-safeish-global-configuration-dsl-5e63).
> fix: get closer to supporting isolated projects.

- src/main/kotlin/com/autonomousapps/internal/models.kt
For path matching the path was dottied too, which feels wrong,
I guess this was just copy & paste and path matching cannot be configured right now anyway,
so just fixed it while changing that code.
The main problem I'm trying to fix with this PR is, that I tried to do `excludeAnnotations("""^\Qorg.spockframework.runtime.model.SpecMetadata\E$""")`
which did not match because the "L" prefix and the ";" suffix from the binary class name are still present.
This PR removes the "L" prefix and the ";" suffix when dottying class names.
> fix: Do not dotty for path matching and remove prefix and suffix from binary class name

- src/functionalTest/groovy/com/autonomousapps/jvm/ApplicationSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/ApplicationProject.groovy
- src/main/kotlin/com/autonomousapps/AbstractExtension.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
Currently if only the `java` plugin is applied, but not one of a small set of known
application-like plugins, a project is not analyzed.
This PR allows to set a property on the extensions that can force application behavior
even if none of the known application-like plugins is applied.
> feat: allow to force app behavior for pure Java projects

- gradle.properties
We build the project in a container with 10G memory and in most cases it hangs in a random place (occasionally it passes successfully).
The main assumption here is default memory settings resolved from environment. After some experiments I've found that this simple change stabilizes the build (reproducible).
> Explicit memory settings

- README.asciidoc
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1099
> docs: README is clear about how to view advice report.

- src/functionalTest/groovy/com/autonomousapps/jvm/CategorySpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/CategoryProject.groovy
- src/main/kotlin/com/autonomousapps/internal/artifacts/DagpArtifacts.kt
- src/main/kotlin/com/autonomousapps/internal/artifacts/Publisher.kt
- src/main/kotlin/com/autonomousapps/internal/artifacts/Resolver.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Plugin.kt
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1159
> fix: DAGP variants have a Category of 'dependency-analysis'.

- src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
- src/main/kotlin/com/autonomousapps/internal/utils/coordinatesStrings.kt
- src/main/kotlin/com/autonomousapps/tasks/ReasonTask.kt
If there is more than one dependency per sourceSet to the same module, but with different capabilities (like default one vs `testFixtures`), the `reason --id :module` explanation is incomplete. It shows only a single explanation of possible routes to dependency instead of all.
The problem is in `ComputeAdviceTask:206`. The `dependencyUsages` object is valid before serialization, but the stored object is first wrapped via `toStringCoordinates` call and there is a problem:
```kotlin
internal fun Map<Coordinates, Set<Usage>>.toStringCoordinates(buildPath: String): Map<String, Set<Usage>> =
map { (key, value) ->
toCoordinatesKey(key, buildPath) to value
}.toMap()
```
Each calculated via `toCoordinatesKey` repeated key is simply lost in favor of the last one which just rewrites the map.
The …
> Incomplete reason explanation on multi capabilities

- src/functionalTest/groovy/com/autonomousapps/jvm/ProjectHealthSpec.groovy
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/ProjectHealthTask.kt
Solves #1114 (only `projectHealth`, but not `buildHealth`).
Prints absolute path of according `build.gradle` of the project module. This can be pretty helpful in large multi-module projects, especially when there is no full matching between module name and submodule directory.
Sample task output:
```
> Task :utilities:projectHealth
/Users/morph/Projects/demo-gradle-multi-module/utilities/build.gradle
Unused dependencies which should be removed:
testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
```
The absolute path is printed intentionally as it seems to be the best trade-off.
This path is recognized in IDEA to open file in "Navigate to File...":
For instance, if relative path is used, there can be ambiguity:
Also, the relative path is not always in parent directory (for …
> #1114 print build path in projectHealth

- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/AndroidBlock.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/DefaultConfig.kt
- testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTestKotlin.kt
I was using testkit to create an android project locally, and I didn't see anyway to overwrite the default values for the `android` block.
> Update test kit to use minSdk, targetSdk, compileSdk, and an equals after applicationId and namespace

- gradle/libs.versions.toml
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This PR adds the latest AGP versions:
- Bump AGP 8.4.x to 8.4.2.
- Add AGP 8.5.0, and mark it as the latest supported version.
- Add AGP 8.6.0-alpha06, and mark it as the latest APG version.
> Add latest AGP versions

- gradle/libs.versions.toml
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
This PR bumps the latest tested AGP version from 8.6.0-alpha06 to 8.6.0-beta01.
> Update latest tested AGP version to 8.6.0-beta01

- gradle/libs.versions.toml
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This PR updates to the latest stable version of AGP: 8.5.1.
The release notes are available here: https://developer.android.com/studio/releases/fixed-bugs/studio/2024.1.1#android-studio-koala-|-2024.1.1-patch-1
> Update latest stable AGP version to 8.5.1

- src/main/kotlin/com/autonomousapps/internal/graph/GraphViewBuilder.kt
- src/main/kotlin/com/autonomousapps/tasks/FindDeclarationsTask.kt
The result of `findDeclarations` and `graphViewX` tasks should be reproducible if inputs are not changed.
Also while debugging there is needed to compare task output (JSON pretty print reformat first) between different executions and it's not convenient to compare non-ordered elements.
> Sort output of graphView and findDeclarations

- src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
kotlin-test is being incorrectly flagged as unused due to how the kotlin plugin manages the dependency.
Fixes #892.
> Bundle kotlin-test to avoid false-positives

- src/functionalTest/groovy/com/autonomousapps/jvm/BundleSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/TestDuplicatedDependenciesSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/ClasspathConfusionProject.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/DuplicatedDependenciesProject.groovy
- src/main/kotlin/com/autonomousapps/internal/utils/coordinatesStrings.kt
- src/main/kotlin/com/autonomousapps/model/declaration/Declaration.kt
- src/main/kotlin/com/autonomousapps/model/intermediates/Usage.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeAdviceTask.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- src/test/kotlin/com/autonomousapps/tasks/ReasonTaskTest.kt
- src/test/kotlin/com/autonomousapps/transform/StandardTransformTest.kt
This resolves an issue when two versions of a dependency are in the various dependency graphs
(e.g., main and test). Without this, we were getting erroneous advice to remove used dependencies,
and then correct advice to re-add used-transitive dependencies. Additionally, the 'reason' results
were confusing and incorrect for a similar reason. As the simplest solution, require full GAV when
requesting the 'reason for' some advice in this circumstance.
There is still one minor issue in the reason output, which is it'll print the shortest path to all
versions of a given dep, even when a specific version is requested.
> fix: when building 'dependencyUsages', merge usages of the same dependency at different versions.

- gradle/libs.versions.toml
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This PR updates the latest stable AGP version to 8.5.2. The release notes are available here: https://androidstudio.googleblog.com/2024/08/android-studio-koala-202411-patch-2-now.html
> Update to AGP 8.5.2

- gradle/libs.versions.toml
- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This PR updates the 8.6.0 branch to rc01, and adds the 8.7.0 branch of AGP to the test matrix.
> Test against AGP 8.7.0-alpha06

- .github/workflows/test.yml
This PR fixes a small issue introduced in https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1218
Currently, the `Maybe add Build Scan URLs as PR comment` step may fail with the following error:
> Fix `test.yml` workflow reporting

- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This PR updates AGP to its latest stable version `8.6.0`, and to its latest alpha version `8.7.0-alpha09`.
> Update to AGP 8.6 stable and 8.7 alpha09

- src/main/kotlin/com/autonomousapps/services/GlobalDslService.kt
I ran into this error while integrating the plugin, took a chance to send a small PR
> Fix typo in AGP missing message

- src/main/kotlin/com/autonomousapps/internal/parse/GradleBuildScriptDependenciesRewriter.kt
- src/test/kotlin/com/autonomousapps/internal/parse/GradleBuildScriptDependenciesRewriterTest.kt
Necessary to support, e.g., version catalog references.
> fix: when rewriting dependencies, don't require a version string.

- src/functionalTest/groovy/com/autonomousapps/jvm/projects/TypealiasProject.groovy
- src/main/kotlin/com/autonomousapps/internal/asm.kt
- src/main/kotlin/com/autonomousapps/model/ProjectVariant.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
This resolves an issue where an annotation library was inaccurately showing up in the
"add to implementation" advice, while also preserving the correct behavior around
Kotlin typealiases.
> fix: improve separation of "annotation" vs "not-annotation" in bytecode analysis.

- src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
> fix: include project description json at both external and internal coordinates.

- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
AGP 8.7 stable seems to bring only bug fixes: https://developer.android.com/build/releases/gradle-plugin
> Update to AGP 8.7 stable and 8.8 alpha04

- gradle/libs.versions.toml
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1297.
> chore: use asm-relocated 9.7.1.0.

- build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
- shadowed/antlr/build.gradle.kts
- shadowed/kotlin-editor-relocated/CHANGELOG.md
- shadowed/kotlin-editor-relocated/README.md
- shadowed/kotlin-editor-relocated/RELEASING.md
- shadowed/kotlin-editor-relocated/build.gradle.kts
- src/main/kotlin/com/autonomousapps/internal/parse/BuildScriptDependenciesRewriter.kt
- src/main/kotlin/com/autonomousapps/internal/parse/GroovyBuildScriptDependenciesRewriter.kt
- src/main/kotlin/com/autonomousapps/internal/parse/KotlinBuildScriptDependenciesRewriter.kt
- src/main/kotlin/com/autonomousapps/tasks/RewriteTask.kt
- src/test/kotlin/com/autonomousapps/internal/parse/GroovyBuildScriptDependenciesRewriterTest.kt
- src/test/kotlin/com/autonomousapps/internal/parse/KotlinBuildScriptDependenciesRewriterTest.kt
Updating the `RewritingTask` to use [kotlin-editor](https://github.com/cashapp/kotlin-editor), which contains an updated grammar for more complex Kotlin Gradle build scripts. The grammar used for parsing Groovy build scripts remains unchanged.
Note: this depends on https://github.com/cashapp/kotlin-editor/pull/17
> Update Kotlin DSL rewriting functionality to use KotlinEditor

- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/DuplicateClasspathSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/DuplicateClasspathProject.groovy
- src/main/kotlin/com/autonomousapps/internal/asm.kt
- src/main/kotlin/com/autonomousapps/internal/models.kt
- src/main/kotlin/com/autonomousapps/model/internal/Capability.kt
- src/main/kotlin/com/autonomousapps/model/internal/ProjectVariant.kt
- src/main/kotlin/com/autonomousapps/model/internal/Source.kt
- src/main/kotlin/com/autonomousapps/model/internal/intermediates/ExplodingJar.kt
- src/main/kotlin/com/autonomousapps/model/internal/intermediates/producer/ExplodedJar.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeProjectViewTask.kt
This dramatically increased size (more than 2x) of this plugin's outputs on disk, and was leading to additional follow-up changes that felt increasingly risky for a marginal use-case. For now, users will have to just rely on the existing `Warning` feature for notification about the duplicate classes issue.
https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1306
https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1310
> revert: feat: check binary compatibility when there are duplicate classes on the classpath.

- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/AndroidBlock.kt
- testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTestGroovy.kt
- testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTestKotlin.kt
This is so you can test android dsl extensions.
https://developer.android.com/reference/tools/gradle-api/8.7/com/android/build/api/variant/AndroidComponentsExtension#registerExtension(com.android.build.api.variant.DslExtension,kotlin.Function1)
> Allow adding custom content to android blocks

- src/functionalTest/groovy/com/autonomousapps/jvm/DuplicateClasspathSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/DuplicateClasspathProject.groovy
- src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
- src/main/kotlin/com/autonomousapps/extension/ProjectIssueHandler.kt
- src/main/kotlin/com/autonomousapps/internal/advice/SeverityHandler.kt
- src/main/kotlin/com/autonomousapps/model/DuplicateClass.kt
- src/main/kotlin/com/autonomousapps/services/GlobalDslService.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/FilterAdviceTask.kt
- src/test/groovy/com/autonomousapps/internal/advice/SeverityHandlerSpec.groovy
> feat: can set severity and filter duplicate class warnings.

- settings.gradle.kts
As discussed [here](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1339#discussion_r1885497306)
> chore: align gradle toolchain resolver syntax with project convention

- settings.gradle.kts
- shadowed/antlr/build.gradle.kts
- shadowed/asm-relocated/build.gradle.kts
- shadowed/kotlin-editor-relocated/build.gradle.kts
- testkit/settings.gradle.kts
The plugin was relocated see [here](https://github.com/GradleUp/shadow/releases/tag/8.3.0).
Version 8.3.0 is very similar to 8.1.1, the gradle requirement was bumped to 8.3 which shouldn't be an issue since you are using 8.11 as far as I can tell.
> chore: adjust shadow plugin coordinates

- src/main/kotlin/com/autonomousapps/internal/ClassNames.kt
- src/main/kotlin/com/autonomousapps/internal/asm.kt
- src/main/kotlin/com/autonomousapps/internal/graph/supers/SuperClassGraphHolder.kt
- src/main/kotlin/com/autonomousapps/model/internal/intermediates/producer/Member.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1358
> fix: cache SuperClassGraph. No need to recompute. Intern more strings.

- build-logic/convention/src/main/kotlin/com/autonomousapps/convention/ConventionPlugin.kt
- build.gradle.kts
- gradle/libs.versions.toml
- src/functionalTest/groovy/com/autonomousapps/jvm/Kotlin2MigrationSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/Kotlin2Migration.groovy
- testkit/gradle-testkit-truth/build.gradle.kts
Replaces https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1371.
> chore: update to Kotlin 2.0.21.

- src/functionalTest/groovy/com/autonomousapps/jvm/projects/DuplicateClasspathProject.groovy
- src/main/kotlin/com/autonomousapps/Flags.kt
- src/main/kotlin/com/autonomousapps/extension/ReportingHandler.kt
- src/main/kotlin/com/autonomousapps/internal/utils/Colors.kt
- src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt
Maybe should just find a library for this...
> fix: support colorizing multiline strings. feat: new dependencyAnalysis.reporting.printBuildHealth DSL option.

- src/main/kotlin/com/autonomousapps/internal/advice/ProjectHealthConsoleReportBuilder.kt
- src/main/kotlin/com/autonomousapps/model/ProjectAdvice.kt
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1381.
> fix: module advice must be 'actionable' to be 'not empty'.

- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This commit updates the project to the latest stable version of AGP: 8.9.0.
It also updates to the latest bugfix version of older versions (8.2.2, 8.8.2) and the latest alpha of the next version (8.10.0-alpha07).
> Update AGP 8.9.0 stable

- src/functionalTest/groovy/com/autonomousapps/jvm/KotlinReflectSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/KotlinReflectProject.groovy
- src/functionalTest/kotlin/com/autonomousapps/kit/gradle/dependencies/Dependencies.kt
- src/functionalTest/kotlin/com/autonomousapps/kit/gradle/dependencies/DependencyProvider.kt
- src/main/kotlin/com/autonomousapps/internal/utils/resolvedDependencies.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/subplugin/RootPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeAllDependenciesTask.kt
Don't suggest moving to runtimeOnly.
Resolves https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1384
> fix: kotlin-reflect must be on the compile classpath.

- build-logic/convention/src/main/kotlin/com/autonomousapps/convention/tasks/GunzipTask.kt
- build.gradle.kts
- gradle/libs.versions.toml
- src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
- src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt
- src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
- src/main/kotlin/com/autonomousapps/tasks/ExplodeJarTask.kt
- src/main/kotlin/com/autonomousapps/tasks/SynthesizeDependenciesTask.kt
- src/main/kotlin/com/autonomousapps/tools/gzip/GunzipTaskOutput.kt
- src/test/kotlin/com/autonomousapps/model/AdviceTest.kt
Using gzip, since it is fast, effective, and an easy drop-in alongside Moshi and Okio.
Starting with exploded-jars.json, which is one of the larger outputs.
Working towards a resolution of https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1395. This gzips one of the largest files we see in DAGP outputs. Let's use this as a test to see if there are any issues with consumers.
> feat: experimenting with compressing intermediates.

- src/main/kotlin/com/autonomousapps/tasks/ArtifactsReportTask.kt
This PR fixes #1360. 
After updating to Kotlin 2.0.21 in our large Android project, the artifact path is sometimes incorrect. This PR applies that same workaround to find the grandparent folder that was previously added for `kotlin/main`.
> fix: issue 1360. Include check for java/main in ArtifactsReportTask

- src/main/kotlin/com/autonomousapps/internal/utils/gradleStrings.kt
This has been a longstanding issue and will probably have multiple knock-on effects. The immediate reason I saw this was that SuperGraph was trying to find nodes built with one version of a graph using nodes from another version of a graph, and failing. This change should sync the two, which ought to also mean fewer outputs in the dependencies directory (no duplication for included build dependencies). I think lots of other code was working around this problem too without realizing it.
> fix: use projectPath, not identityPath, for included build coordinates.

- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This PR:
- Bumps the latest stable AGP version to 8.10.0.
- Updates AGP 8.9 to use the latest bug fix version (8.9.2).
- Starts testing against the latest alpha (8.11.0-alpha09).
- Include Gradle 8.13 and 8.14.
- Tests against Gradle 8.14 instead of 8.12 (AGP 8.11 seems to require Gradle 8.13+).
> Update latest stable AGP to 8.10.0

- src/functionalTest/groovy/com/autonomousapps/android/projects/CouldBeAndroidProject.groovy
- src/main/kotlin/com/autonomousapps/model/ModuleAdvice.kt
- src/test/kotlin/com/autonomousapps/internal/reason/ModuleAdviceExplainerTest.kt
Prevents "should be jvm" advice for projects that cannot be since they have android dependencies.
@autonomousapps and I chatted on slack about it and for now decided to try fixing most of the issues by setting the weight of using android dependencies to 100 so that any module with android deps never gives the "should be jvm" advice
see also https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1417
> Set has android dependencies weight to 100

- src/main/kotlin/com/autonomousapps/extension/BundleHandler.kt
- src/main/kotlin/com/autonomousapps/extension/Issue.kt
Allows using version catalogs like the following:
```toml
com-example = {}
com-example-support = {}
```
Where you must use `asProvider()` to pass `libs.com.example` to DAGP DSL
Closes #1281
> Add ProviderConvertible support

- src/functionalTest/groovy/com/autonomousapps/jvm/ProjectHealthSpec.groovy
Build Scan: https://scans.gradle.com/s/csbapb2cecxwo/tests/overview
Gstrings are surprising... The last line would not be correctly handled...
Besides this issue, multiple solutions are available for the file path:
- remove the manual string path concatenation with proper file resolving
- replace `ProjectHealthTask`'s `buildFilePath` input with `invariantSeparatorsPath`
I chose the first to avoid changing production code.
> Fix ProjectHealthSpec on Windows environments

- src/functionalTest/groovy/com/autonomousapps/jvm/NestedProjectsSpec.groovy
Build Scan: https://scans.gradle.com/s/uwlpzccsbxhuy/tests/overview
This time, the issue comes from the fact that:
- `Circular dependency between the following tasks` log message is being printed by Gradle itself, and therfore following the `System.lineSeparator()`
- Groovy strings are using `\n` by default
> Fix NestedProjectsSpec on Windows environments

- testkit/gradle-testkit-plugin/src/main/kotlin/com/autonomousapps/GradleTestKitPlugin.kt
Here is a Build Scan of the errors: https://scans.gradle.com/s/3plpnsp5mibti/tests/overview?outcome=FAILED
This comes from the injected string in the generated settings.gradle not respecting Java syntax: `maven { url = 'E:\IdeaProjects\dependency-analysis-gradle-plugin\build\functionalTestRepo' }`
This is almost identical to this PR:
- https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1045
That being said, I chose to not try to "escape" the String like it was achieved in the PR because:
- I could not re-use the function directly
- escaping characters to respect Java's [specification](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.10.6) is a bit more involving, and only escaping backslash feels wrong.
This will result in:
`maven { url = …
> Fix JvmSpec functionalTest on Windows environments

- build-logic/convention/src/main/kotlin/com/autonomousapps/convention/ConventionPlugin.kt
https://scans.gradle.com/s/uoprp4zoprffc/failure
Per `./gradlew :tasks --group publishing`, the task that can't be found definitely exists. So I think maybe it is added lazily. Let's see!
> chore: fix snapshot publishing by making task dependency more lazy.

- build-logic/convention/src/main/kotlin/com/autonomousapps/convention/ConventionPlugin.kt
https://scans.gradle.com/s/pamquleoubdvq/failure#1
Follow-up on https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1453.
> chore: try again to fix snapshot publishing by making even more task dependencies lazy.

- src/functionalTest/groovy/com/autonomousapps/jvm/RegexExclusionsSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/jvm/projects/RegexExclusionsProject.groovy
- src/main/kotlin/com/autonomousapps/extension/Behavior.kt
- src/main/kotlin/com/autonomousapps/extension/Exclusion.kt
- src/main/kotlin/com/autonomousapps/extension/Issue.kt
- src/main/kotlin/com/autonomousapps/model/DuplicateClass.kt
- src/main/kotlin/com/autonomousapps/model/ModuleAdvice.kt
- src/main/kotlin/com/autonomousapps/tasks/DetectRedundantJvmPluginTask.kt
- src/main/kotlin/com/autonomousapps/tasks/FilterAdviceTask.kt
Something we run into semi-frequently is that DAGP will correctly indicate a used dependency that should be declared but it violates other checks that forbid "internal" dependencies being declared outside of their "sibiling" modules. This becomes particularly annoying inside projects using Anvil where all of the uses of the transitive dependencies are inside generated sources or bytecode. While the advice given by the plugin may be correct in those cases, it is not particularly useful and results in an excessively large `dependencies` block.
> Allow excluding violations by regex patterns

- PUBLISHING.asciidoc
- README.asciidoc
- build-logic/convention/src/main/kotlin/com/autonomousapps/convention/DagpExtension.kt
- build-logic/settings.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
- src/smokeTest/kotlin/com/autonomousapps/fixtures/SimpleProject.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/Repository.kt
- testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTestGroovy.kt
- testkit/gradle-testkit-support/src/test/kotlin/com/autonomousapps/kit/render/ScribeTestKotlin.kt
- testkit/settings.gradle.kts
See also https://github.com/vanniktech/gradle-maven-publish-plugin/releases/tag/0.33.0
> feat: move snapshot publishing to new central.sonatype.com repo.

- src/functionalTest/groovy/com/autonomousapps/android/TestFixturesSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/TestFixturesAddTransitiveProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/TestFixturesDuplicatedWithMainProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/TestFixturesUnusedDependencyProject.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/TestFixturesWithAbiProject.groovy
- src/functionalTest/kotlin/com/autonomousapps/kit/gradle/dependencies/DependencyProvider.kt
- src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
- src/main/kotlin/com/autonomousapps/internal/utils/collections.kt
- src/main/kotlin/com/autonomousapps/model/declaration/internal/Configurations.kt
- src/main/kotlin/com/autonomousapps/model/source/SourceKind.kt
- src/main/kotlin/com/autonomousapps/subplugin/ProjectPlugin.kt
- src/main/kotlin/com/autonomousapps/tasks/ComputeUsagesTask.kt
- src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/AndroidBlock.kt
- testkit/gradle-testkit-support/src/main/kotlin/com/autonomousapps/kit/gradle/android/TestFixturesOptions.kt
I added a unit test reproducing the issue and came up with a solution. This PR adds support for android `testFixtures` configuration. 
Notes:
- I'm not quite sure about which test cases I should add except the most basic one. Feel free to suggest anything :)
- Although I don't like that `Quadruple` became a `Pentuple`, I think this is out of scope for this fix
> Fix issue #1323: Incorrect advice for testFixtures configuration in Android project

- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This PR updates:
- AGP 8.9 to the latest fix (8.9.2 → 8.9.3).
- AGP 8.10 to the latest fix (8.10.0 → 8.10.1).
- AGP 8.11 to the stable version (8.11.0-alpha09 → 8.11.0).
- Gradle 7.6 to the latest fix (7.6.2 → 7.6.5).
- Gradle 8.14 to the latest fix (8.14 → 8.14.2).
> Update AGP to the latest stable version (8.11.0)

- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
- src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
This PR updates the tested supported AGP versions:
- 8.11.0 → 8.11.1
- 8.12.0-alpha08 → 8.12.0
- Introduce 8.13.0-alpha03
> Update to AGP 8.12 stable

- src/main/kotlin/com/autonomousapps/internal/advice/AdvicePrinter.kt
- src/main/kotlin/com/autonomousapps/internal/parse/AdviceFinder.kt
- src/main/kotlin/com/autonomousapps/internal/parse/KotlinBuildScriptDependenciesRewriter.kt
- src/main/kotlin/com/autonomousapps/tasks/RewriteTask.kt
- src/test/kotlin/com/autonomousapps/internal/parse/GroovyBuildScriptDependenciesRewriterTest.kt
- src/test/kotlin/com/autonomousapps/internal/parse/KotlinBuildScriptDependenciesRewriterTest.kt
The `fixDependencies` task failed when encountering type-safe project accessor syntax in both Kotlin and Groovy DSL:
- **Parser failures**: Type-safe accessors like `implementation(projects.myModule)` weren't properly handled
- **Advice matching failures**: Type-safe accessors weren't correctly mapped to project advice
- **Limited DSL support**: No consideration for different Groovy DSL syntax styles
This prevented teams using modern Gradle type-safe accessor patterns from leveraging the plugin's automatic dependency management capabilities.
- [e2763f2](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1522/commits/e2763f2170c350b5ced5c0be931682c9f14ab8cb) <-- Initial implementation
- [466df9b](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/ …
> Add type-safe accessor support for fixDependencies task

- src/main/kotlin/com/autonomousapps/internal/parse/explodeAndroidResSource.kt
My modification moved the container variable into the method that generates ExplodedRes, ensuring that the reference relationships of individual resources are not polluted by project-level reference relationships.
> fix resource ref problem

- src/functionalTest/groovy/com/autonomousapps/android/AndroidFileMutationSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidFileMutationProject.groovy
- src/main/kotlin/com/autonomousapps/tasks/CodeSourceExploderTask.kt
Fixes #1337 
I would think that the cache would get invalidated because of the file change, but either it doesn't, or something else is broken. In the meantime, this should stop the errors, and provide correct behavior.
> Don't try to parse files that don't exist

- src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
- src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
This PR updates the tested supported AGP versions:
- 8.12.0 → 8.12.2
- 8.13.0-alpha03 → 8.13.0
This also updates Gradle 9.1 to the RC2 version.
> Update to AGP 8.13 stable
